### ISSUE TITLE
[SIDE MENU] Licences

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#10]
Il faudrait mettre à jour les infos sur la page d'accueil afin d'indiquer
que la licence CC-BY-SA est itilisée pour les données protégées au titre du droit d'auteur
Que la licence ODBL est utilisée pour les données qui ne relèvent pas du droit d'auteur

**Comment by maximenathan** [comment]
@urien Peux tu détailler avec un screenshot et donner le texte exact  ?

**Comment by urien** [comment]
Cela pourrait ressembler à cela
![Sans titre 1](https://user-images.githubusercontent.com/1165144/135446282-40556c94-e2d8-4db9-acc5-3a36f8d6e3e6.png)



Avec un texte dans une info bulle 
pour CC-BY-SA : Sauf mention contraire la licence CC-BY-SA s'applique pour les documents et textes soumis au droit d'auteur
pour ODBL : la licence ODBL s'applique a l'ensemble des données qui ne relèvent pas du droit d'auteur
avec pour ODBL un lien vers https://opendatacommons.org/licenses/odbl/
