### ISSUE TITLE
Permettre en export en CSV

### ISSUE THREAD

**Issue by Xtof054** [GrottoCenter/grottocenter-front#1033]
Bonjour,

**Is your feature request related to a problem? Please describe.**
En tant qu'auteur de Documents our le BBS, je souhaite pouvoir transmettre la liste des saisies effectuées aux éditeurs ^pour lesquels j'ai effectué des saisies.

**Describe the solution you'd like**
Dans le tableau de bord d'un auteur de Documents, proposer la possibilité d'exporter en format CSV la totalité des saisies effectuées afin de pouvoir informer les éditeurs.

Cordialement,
Christophe

**Comment by urien** [comment]
Salut Christophe. Il me semble que c'est déjà possible. Si tu fais une recherche des documents en mettant ton pseudo dans Pseudo du contributeur
![{99C0A636-FAEB-4C4F-B2A8-DB4FF7E022DD}](https://github.com/user-attachments/assets/3cab8d32-087f-4379-abf4-1914f8f0a3f2)

**Comment by Xtof054** [comment]
Ah oui, effectivement. Je n'avais pas pensé à passer par la recherche... Cela marche bien.
