### ISSUE TITLE
[SIDE MENU] Update items

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#17]
Avec les développements récents et à venir il faudrait reprendre la barre de menu
![image](https://user-images.githubusercontent.com/1165144/135513488-e3b35936-3cee-4c4f-8f28-29fb9da7fd0f.png)
La boite à outils est vide et elle ne va pas servir dans les prochains mois : il faudrait l'enlever

Le menu document devrait être également supprimé : la validation de document est désormais accessible depuis le tableau de bord

Il faudrait faire un menu créer (ou un bouton + dans la barre de menu ou en bas à droite de l'écran : les propositions sont bienvenues !)
A partir de ce bouton "créer" on accedera au sous menu qui s'appelle actuellement "ajouter un document BBS". Dans les prochains jours on rajoutera les entrées, réseaux, organisations, massifs

Dans le menu la carte sera mise en premier

Le menu accueil est a enlever

Un menu A propos est mis en dernier et donne accès à la page d'accueil actuelle

**Comment by bsoufflet** [comment]
Oui, ajouter un bouton "+ Contribuer" qui contiendrait pour l'instant un seul "sous lien" qui serait "ajouter un document BBS".

**Comment by Clm-Roig** [comment]
Je fais un récap, on a un peu avancé au final sur cette issue

> La boite à outils est vide et elle ne va pas servir dans les prochains mois : il faudrait l'enlever

Fait :heavy_check_mark: 

> Le menu document devrait être également supprimé : la validation de document est désormais accessible depuis le tableau de bord

ça ne me choque pas qu'on puisse y accéder par 2 endroits différents personnellement, je trouve ça pratique de passer par le menu.

> Il faudrait faire un menu créer (ou un bouton + dans la barre de menu ou en bas à droite de l'écran : les propositions sont bienvenues !) 

Fait :heavy_check_mark: 

> A partir de ce bouton "créer" on accedera au sous menu qui s'appelle actuellement "ajouter un document BBS". Dans les prochains jours on rajoutera les entrées, réseaux, organisations, massifs

Ok à faire. 

> Dans le menu la carte sera mise en premier

Je préfère le dashboard en premier mais bon, j'ai une utilisation de GC qui n'est pas la même que la majorité je pense :sweat_smile: 

> Le menu accueil est a enlever

Oui pourquoi pas, on a le logo au-dessus.

> Un menu A propos est mis en dernier et donne accès à la page d'accueil actuelle

Hum... A propos ne doit pas renvoyer vers l'accueil, je ne vois pas la logique derrière.  
(pour le renvoi vers l'accueil, cf point précédent)

**Comment by urien** [comment]
Ce sujet nécessite une nouvelle réflexion et la rédaction d'un nouveau ticket
