### ISSUE TITLE
[PERSON] View

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#18]
Il serait utile d'avoir une page publique qui décrive les personnes

L'URL serait de type `grottocenter.org/ui/persons/12345678`

Les informations présentes seraient :
- name
- surname
- nickname
- langage

Ainsi qu'une liste de ressources qui sont liés à la personne :
- Les documents dont les personnes sont les auteurs
- Le nombre de contributions à Grottocenter
- éventuellements d'autres informations à déterminer comme l'appartenance à une organisation, le fait d'avoir visité une cavité...

**Comment by bsoufflet** [comment]
@Clm-Roig : Les liens décrit par @urien dans la description sont ils accessible via l'API ?

**Comment by Clm-Roig** [comment]
Oui l'API est déjà en place ! Il y a un contrôle de qui demande les données, on a au minimum accès à ça : 
![image](https://user-images.githubusercontent.com/20704943/136164700-4f29d20b-5036-4b53-8162-8241a9166e8e.png)

**ROUTE à utiliser**

`/api/v1/cavers/1234567`

**Comment by Clm-Roig** [comment]
Je me suis permis de reformuler ton message @urien sans rien enlever sur le fond de ton propos : c'est juste pour y voir plus clair (listes au lieu de phrases).

>     - country (le pays est une donnée personnelle définie comme pouvant être communiquée par Grottocenter)

On n'a pas cette information à propos des personnes. Ce qu'on a c'est le `language` uniquement. Il va falloir mettre à jour les conditions d'utilisation de GC donc non ?

**Comment by Clm-Roig** [comment]
> L'URL serait de type grottocenter.org/ui/persons/12345678

Est-ce qu'on bascule sur "person" au lieu de "caver" ? Pour l'API, ce serait peut-être une bonne idée aussi je pense. 

Ultérieurement, autant pour l'API que pour le client, on peut aussi imaginer avoir des URLs plus spécifiques comme `/users` et `/authors` pour différencier les 2 types de compte existants dans GC. Ce serait des cas particuliers de `/persons`, les 3 routes seraient quasiment similaires mais toutes fonctionneraient.

**Comment by urien** [comment]
Passer a person est une bonne idée.
On peut afficher le language, je vais mettre à jour les infos.
Je pense qu'il ne faut qu'une seule route pour toutes les personnes car les groupes sont poreux et les URL doivent être immuable pour une entité donnée

**Comment by lageta** [comment]
Est-ce que l'on devrait faire apparaître l'appartenance de la personne à un ou plusieurs groupes (Administrator,
Moderator, User, Visitor, Leader) ?

**Comment by urien** [comment]
Pourquoi pas. C'est une bonne idée. Les visiteurs n'ont pas de compte et les personnes qui ont comme mel no@mail.com (ou un truc de ce genre) sont des auteurs

**Comment by Clm-Roig** [comment]
Pour être précis, la règle avec les dernières modifs (https://github.com/GrottoCenter/Grottocenter3/pull/764) c'est que les cavers avec un email qui finit en `@mail.no` sont des auteurs et les autres des utilisateurs.
