### ISSUE TITLE
[DOC SUBMISSION] Add more document types

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#19]
En base de données une liste de types est définis pour les documents.
Coté applicatif seuls certains de ces types sont proposés.
Cela va devenir handicapant maintenant qu'il est possible de proposer des fichiers.
Il faudrait pouvoir choisir parmi tous les types de documents, éventuellement en débutant la liste par les types Collection, Numéro, Article.
![image](https://user-images.githubusercontent.com/1165144/136397297-d7688b3c-1c35-4762-9f82-692165225391.png)

**Comment by Clm-Roig** [comment]
Actuellement, les 4 types de documents proposés sont hardcodés dans le client. Cela est dû au fait que de nombreux champs du formulaire sont dépendans du type choisi (certains disparaissent / apparaissent, d'autres sont obligatoires ou facultatifs). 

Il faudrait demander à l'api la liste de tous les types possibles (cette route n'existe pas encore, elle se nommerait `GET /api/v1/documents/types`). 

Enfin, chaque type de document devra faire l'objet d'une réflexion pour savoir quel(s) champ(s) est obligatoire / facultatif et affiché / masqué, comme cela a été fait pour les 4 premiers.

**Comment by urien** [comment]
J'ai repris le tableau sur lequel on avait travaillé pour les 4 premiers types
https://docs.google.com/spreadsheets/d/1jtG6PEPwtKs6WuQ-e3BOFQD5nkFFCID10qnCNJL4J2U/edit?usp=sharing
Il est possible pour tout le monde de l'éditer
Je vais faire une proposition pour le compléter

**Comment by urien** [comment]
Une première approche serait de mettre le même fonctionnement que les textes pour tous les nouveaux types de document rajoutés
