### ISSUE TITLE
licenses are not available / document type

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#20]
J'essaye de rajouter un fichier sur azure.grottocenter.org
il ne m'est pas possible de selectionner une licence le champ licence est vide
Si j'indique qu'il existe un document qui autorise la publication  j'ai la possibilité de choisir parmi les bibliographies. Il faudrait que tous les documents ayant comme titre bibliographie soient passés au type TEXTE et non AUTORIZETOPUBLISH ou que le front affiche bien les documents ayant ce type

**Comment by AxelCanton** [comment]
Pour les formats de ficher et les licenses c'est normal ! La PR de l'API n'a pas été merge et j'y ai ajouté quelques routes, donc ça justifie les erreurs 404.

Pour ce qui est des types je comprends pas trop, normalement ça n'affiche que ceux qui ont le type AUTHORIZE_TO_PUBLISH, si le problème est au niveau de la bdd (le type est incorrect pour certains) c'est bien au niveau de la bdd qui faut faire la modification.

**Comment by urien** [comment]
Merci Axel,
On a bien un message d'alerte qui passe rapidement
Pour les licences on a une boite vide 
![image](https://user-images.githubusercontent.com/1165144/136808213-623e5308-8cdd-4b7c-918f-d3c18d3f03ef.png)
Pour les documents de type AUTHORIZE_TO_PUBLISH on a toute une liste de Bibliographie.
J'avais un problème assez proche avec la validation des documents après que tu ai mis en place la possibilité d'éditer un document. Toutes les bibliographies étaient dans la liste des fichiers à valider. @maximenathan a corrigé ce problème. C'est peut être quelque chose du même genre
![image](https://user-images.githubusercontent.com/1165144/136808410-9820242e-ba13-4ecc-b88e-731b5eab4a9f.png)

**Comment by AxelCanton** [comment]
Que le champ des licences affiche une boîte vide est normal, comme j'ai dit au dessus, la route qui permet de récupérer la liste de licences n'est pas encore merge.

Il faudrait pouvoir regarder la liste des documents qui ont comme type AUTHORIZE_TO_PUBLISH dans le base de données de prod pour pouvoir comprendre le problème.

**Comment by urien** [comment]
Cela semble réglé
