### ISSUE TITLE
[ADV SEARCH] Nombre de resultats non-visibles sur mobile + ajuster pagination

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/grottocenter-front#259]
testé ce matin (après déploiement):

Sur mobile (grand iphone)
- Je ne vois pas où le nombre de résultat d’une requete est affiché. je ne sais pas s’il y a 10, 50 ou 200 résultats. Le nombre est "hors ecran". Sur PC, c'est bon

- il y a la possibilité d’afficher 5 , 10 ou 20 résultats par page. on pourrait proposer plutot 5, 10, 100 (en cas de recherche desktop) 

- il serait bien d'avoir la possibilité d'accéder directement à la Xieme page de résultat. Actuellement, s'il y a 900 résultat, je suis obligé de les passer 20 par 20. Et de recommencer si j'ai le malheur de quitter la page et revenir plus tard

**Comment by urien** [comment]
Nous allons organiser une séance avec 2 étudiants de M1 qui vont présenter
l'utilisation de Grottocenter et collecter les besoins des utilisateurs
afin d'établir une liste de développements qu'ils vont prendre en charge.
Il est prévu qu'une séance soit organisée le vendredi 10 décembre à 20h
concernant l'usage du BBS. Est-ce que tu serais intéressé ?

**Comment by Ospeleo** [comment]
Je serai à l’étranger et injoignable à cette heure
