### ISSUE TITLE
[ENTRANCE Create] If not exist : create CAVE

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#261]
Quand on créé une cavité (entry dans la bdd) il est actuellement nécessaire de l'associer à un réseau (une cave dans la BD) déjà existant.
Dans la plupart des cas, la création d'une entrée doit également générer la création d'une nouvelle cavité qui aura le nom et les données fournies à l'entrée.
Je propose la modalité suivante
![issue](https://user-images.githubusercontent.com/1165144/142983423-3e1cb14c-1fe6-4f19-a070-4531931f0897.png)
Si la nouvelle entrée est associée à un réseau il faut le sélectionner. Si on valide en laissant le champ vide cela créé automatiquement une nouvelle cavité

**Comment by urien** [comment]
Il faut coté front changer la recherche sur les réseaux par la recherche sur toutes les cavités, de manière à pouvoir soit créer un nouveau réseau soit associer la cavité à un réseau existant

**Comment by Clm-Roig** [comment]
On peut fermer ça @urien non ? Désormais la création de cavité inclue les 2 cas.

**Comment by urien** [comment]
Question traitée
