### ISSUE TITLE
[ENTRANCE Create] Automatic retrieval of administrative information

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#262]
La saisie des informations de localisation de l'entrée 
![image](https://user-images.githubusercontent.com/1165144/142984225-1489d618-faa9-44ed-a602-ab532d1375fa.png)
permettrait de renseigner les informations de localisation administratives (pays, région, département,ville)
 Cela se fera à partir des outils mis en place
https://github.com/GrottoCenter/grottocenter-api/pull/1160

Le résultat sera affiché dans la langue choisie par l'utilisateur pour Grottocenter, le nom dans les différentes langues étant stockés dans la table iso_3166_2. Il conviendrait de faire la même chose avec la table des pays

**Comment by bsoufflet** [comment]
@BastienBoymond : Voici une issue simple qui pourrait t'intéresser ?

**Comment by bsoufflet** [comment]
@Clm-Roig : Pour cette issue il faut peut-être juste aller récupérer le "connecteur" à l'API dans le travail réalisé par les étudiants non ?

**Comment by Clm-Roig** [comment]
Il y a quand même quelques commentaires sur la PR qui n'ont pas été traités (utilisation de Redux notamment). 

Le code de l'API pourrait faire l'objet de quelques améliorations : il est tout en promises alors qu'on utilise quasiment plus que des await.

**Comment by urien** [comment]
Done
