### ISSUE TITLE
[ENTRANCE Create] retrieve the coordinates by moving the cursor on the map

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#263]
![image](https://user-images.githubusercontent.com/1165144/142995208-5221d2cd-b247-4839-8c48-039c894c8f89.png)

**Comment by bsoufflet** [comment]
@BastienBoymond : Voici une issue simple qui pourrait t'intéresser ?

**Comment by urien** [comment]
Fait par Vincent
