### ISSUE TITLE
[ENTRANCE Create] Auto fetch the language of the entrance name using the current Grottocenter language

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#264]
![image](https://user-images.githubusercontent.com/1165144/142995499-a526d9db-0158-4993-90c4-5b1c24dfb741.png)

By default the language of the entrance name should be set to the language of the current user.
However, the user still need to be able to select an other language if he want to. Indeed, some contributor may want to enter the entrance name as it is in the origin country (for example a french caver working on caves in Thailand)

**Comment by bsoufflet** [comment]
@BastienBoymond : Voici une issue simple qui pourrait t'intéresser ?

**Comment by BTHOM** [comment]
Merci à Benjamin pour la reformulation du besoin.
En effet la langue utilisée pour nommer une entrée n'est pas nécessairement la langue du contributeur.
Par exemple, je parle français mais je n'utiliserais pas la traduction française de "Mammoth Cave".

ATTENTION : La situation est encore différente dans le cas d'une langue utilisant un alphabet spécifique (tel que le thaï, cité par Benjamin). Dans un tel ca, le contributeur aura sans doute besoin de saisir non seulement le nom de la cavité en Thaï, mais aussi la translittération dans son alphabet, voire la traduction dans sa langue. Qu'est il prévu dans la base de données pour stocker ces différentes transcriptions du nom de l'entrée ? Dans OSM, par exemple, il est possible de créer autant de traduction du nom de l'objet que nécessaire.

**Comment by urien** [comment]
Fait par Vincent
