### ISSUE TITLE
[MAP] Problems with not correctly placed/sized elements

### ISSUE THREAD

**Issue by louis-cuny** [GrottoCenter/grottocenter-front#28]
- [x] The breadcrump has a curious height with text and icons on different sizes.

- [ ] The converter tool is out of the screen

![image](https://user-images.githubusercontent.com/13121784/107131833-5ef1db80-68da-11eb-9c51-0f5fecd28450.png)
![image](https://user-images.githubusercontent.com/13121784/107131842-674a1680-68da-11eb-91db-e526b7910dc9.png)

**Comment by bsoufflet** [comment]
On the new Azure app the breadcrumb has been removed.
