### ISSUE TITLE
[ENTRANCE] Special treatment for sensitive entrance

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-front#299]
## Restriction des données
L'attribut `isSensitive` d'une entrée de cavité définit si l'entrée est sensible. Cela signifie que, pour sa préservation, certaines de ses données sont altérées par l'API voire même supprimées : 

- Les coordonnées (`latitude` et `longitude`) renvoyées sont celles de la commune à laquelle est rattachée l'entrée. 

- Les contributions "Locations" des utilisateurs ne sont pas renvoyées.

Une mention indique sur la page que les coordonnées sont faussées. On peut imaginer un bandeau rouge bien visible ainsi que la latitude / longitude en rouge et gras avec un Tooltip.

Note : les administrateurs de GC sont les seuls à avoir accès à l'intégralité des données. Cela n'a aucune importance ici : le client doit juste lire la valeur `isSensitive` et faire les affichages nécessaires sans se soucier du rôle de l'utilisateur. L'API aura déjà filtré les données de manière appropriée.

## Affichage sur la page de la cavité
- Faire figurer sur la page la mention "cavité à accès restreint"
- En passant la souris sur la mention "cavité à accès restreint" on aurait une phrase qui explique ce que c'est. Le texte pourrait être "Cette cavité nécessite des mesures de protection particulières. Nous ne communiquons pas sa localisation précise sur Grottocenter. Vous pouvez contacter les organisations indiquées pour avoir davantage d'informations."
- Sous les coordonnées serait affiché :
  - 🔴 En rouge : cavité à accès restreint - coordonnées faussées > pour les cavités avec une précision des coordonnées = 0
  - 🟠 En orange : précision des coordonnées inconnue > pour les cavités qui n'ont pas de valeur dans le champ précision des coordonnées
  - 🟢 En vert : précision des coordonnées : X m > pour les cavités qui ont la valeur X enregistrée dans le champ précision des coordonnées

### ⚠️ Nécessite que https://github.com/GrottoCenter/grottocenter-front/pull/288 soit validée⚠️ 
Lors de l'édition d'une entrée, les utilisateurs peuvent cocher un bouton "Marquer cette cavité comme sensible". Avant de soumettre cette modification, un pop-up de confirmation apparaîtra. 

### ⚠️ Nécessite que https://github.com/GrottoCenter/grottocenter-front/pull/288 soit validée⚠️ 
Une cavité sensible ne peut être désensibilisée que par un administrateur lors de l'édition d'une entrée.

**Comment by urien** [comment]
Je propose que les utilisateurs aient accès a un bouton a cocher "Cavité sensible". Eventuellement faire un pup up avec un message de confirmation.
Une fois le bouton coché seul les administrateurs peuvent le décocher.
Depuis que j'ai fait ce ticket j'ai réfléchi a une nouvelle solution coté back.
L'enregistrement d'une cavité sensible conduit  a stocker les coordonnées dans une table qui n'est pas accessible via les apis et a utiliser des apis externe pour trouver la commune correspondant aux coordonnées fournies et de stocker les coordonnées correspondant à la commune dans la table de l'entrée.
Le champ sur la précision serait passé à 0 (si ce n'est pas la valeur par défaut)
Une cavité qui serait "désensibilisée" verrait ses coordonnées réelles recopiées dans la table de l'entrée.
Pour les cavités sensibles je propose que le champ accès ne soit pas accessible via les apis et ne soit pas visualisé sur la page. Une mention indique sur la page que les coordonnées sont faussées (liée au fait que la précision est à 0). cette info est disponible pour les utilisateurs de l'API

**Comment by urien** [comment]
En complément il faudrait pouvoir créer des cavités sensibles en masse (par pays) et automatiser le remplissage des informations administratives avec impossibilité (sauf pour les administrateurs) de modifier le pays, voir la région

**Comment by Clm-Roig** [comment]
J'ai mis à jour mon premier message sur cette issue en reprenant tes idées @urien. J'ai quelques questions à te poser pour clarifier quelques détails (dans un prochain commentaire).

**Comment by Clm-Roig** [comment]
Je ne comprends pas trop les points suivant... L'idée de la table "non-accessible via les APIs" c'est par rapport au mail de Peter qui mentionnait une base de données hors ligne pour plus de sécurité ?


> La sensibilisation d'une cavité conduit à :
> 
>     1. stocker les coordonnées dans une table qui n'est pas accessible via les APIs
> 

Comment stocker les coordonnées dans une table hors ligne... ? Je ne vois pas de solution, à part que les admins aient un accès manuel à la base hors-ligne et rentrent les données à la main directement dedans.

>     2. utiliser des APIs externes pour trouver la commune correspondant aux coordonnées fournies
> 
>     3. stocker les coordonnées correspondant à la commune dans la table de l'entrée.
>

J'imagine que ceci implique que les PRs suivantes soient mergées ?
https://github.com/GrottoCenter/Grottocenter3/pull/271
https://github.com/GrottoCenter/Grottocenter3/pull/273

**Comment by urien** [comment]
`1. stocker les coordonnées dans une table qui n'est pas accessible via les APIs`
Je pense aux apis publiques, il faudra limiter l’accès à cette table aux seuls administrateurs

oui, https://github.com/GrottoCenter/grottocenter-api/pull/271
https://github.com/GrottoCenter/grottocenter-api/pull/273 doivent être finalisés et mergés.

Je pense que pour répondre à la demande de Peter il faudrait aussi mettre en place une notification aux modérateurs pour les modifications réalisées sur les cavités d'un pays

**Comment by Clm-Roig** [comment]
> `1. stocker les coordonnées dans une table qui n'est pas accessible via les APIs` Je pense aux apis publiques, il faudra limiter l’accès à cette table aux seuls administrateurs
> 

On a qu'une seule API et elle est publique. La seule possibilité (que tu mentionnes) est donc bien de passer par cette API mais avec vérification des droits pour accéder à la table, comme on le fait pour énormément de fonctionnalités, via la table _t_right_. C'est bien ça ?

> Je pense que pour répondre à la demande de Peter il faudrait aussi mettre en place une notification aux modérateurs pour les modifications réalisées sur les cavités d'un pays. 

Pourquoi pas mais à discuter sur une autre issue que celle-ci : c'est indépendant.

**Comment by urien** [comment]
Oui
