### ISSUE TITLE
[CAVE NETWORK PAGE] 

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#30]
A partir de la page existante
https://grottocenter.org/ui/caves/75496
Changer le texte Visible Entries par Network entries et afficher dans la liste le nom des entrées associées à cette cave. en cliquant sur le nom on ouvre une nouvelle fenêtre correspondant à la page de l'entrance correspondante
Supprimer les champs dans la partie de droite de la fenêtre : actuellement aucun contenu détaillé n'est associé aux réseau

**Comment by Clm-Roig** [comment]
@urien Quelle(s) différence(s) faisons nous entre l'affichage d'un réseau et d'une cavité ? J'en vois qu'une mineure c'est la gestion de l'URL. 

Je propose que si on requête /caves/:id alors que c'est un réseau, on redirige automatiquement (sans en informer l'utilisateur même ?) vers /networks/:id (et réciproquement). 
L'affichage sera fait avec le même composant, je ne parle vraiment que de l'url.

**Comment by urien** [comment]
Pour un réseau il faut afficher la liste des cavités.. et pour la cavité le réseau eventuel 
C'est la seule difference

**Comment by Clm-Roig** [comment]
> Pour un réseau, il faut afficher la liste des cavités.. et pour la cavité le réseau éventuel.

Alors de ce que j'ai compris des termes qu'on utilise désormais, il me semble que c'est plutôt : 
> Pour un réseau il faut afficher la liste des entrées... et pour l'entrée le réseau éventuel.

Sinon je veux bien qu'on mette à jour le document qui décrit [le vocabulaire dans GC](https://github.com/GrottoCenter/Grottocenter3/wiki/Vocabulary).

ça rentre aussi en contradiction avec le document "proposition cavités - réseaux pour Grottocenter V3" : 
![image](https://user-images.githubusercontent.com/20704943/159920577-bffc722d-b610-4316-91ba-707572175037.png)

**Comment by urien** [comment]
Pour les utilisateurs (donc le texte qu'on leur propose) il y a des cavités et des réseaux
Les réseaux sont des caves avec plusieurs entrances, donc pas toutes les caves
Les cavités correspondent bien a un ensemble entrance + cave en base de données. Coté api c'est la route entrance qui va fournir les données sur l'entrance et sur la cave associée

**Comment by urien** [comment]
Je viens de reformuler la description de cavité et réseau

**Comment by Clm-Roig** [comment]
Ok c'est plus clair. 

Juste pour être sûr qu'on s'est compris, on est d'accord que "Pour un réseau, il faut afficher la liste des cavités" c'est au sens "Pour un réseau, il faut afficher la liste des cavités reliées aux entrées du réseau" ? Un réseau c'est une cave avec une liste d'entrances. Après certes, ces entrances sont chacune associées à une cave. 
Mais "au premier degré", un réseau a une liste d'entrances uniquement.

Un réseau => plusieurs entrées => plusieurs cavités

**Comment by urien** [comment]
Oui. Tu peux mettre comme titre "liste des cavités faisant partie du réseau" et affiche le nom des entrances avec un lien vers la page de l'entrance
