### ISSUE TITLE
[ADVANCED SEARCH] Highlight research on specific fields

### ISSUE THREAD

**Issue by hafidinferno** [GrottoCenter/grottocenter-front#301]
Suite aux tests utilisateurs qu'on a mené, les utilisateurs ont demandé à ce que le bouton "recherche dans les champs spécifiques" soit plus mis en évidence 
![Screenshot (151)_LI](https://user-images.githubusercontent.com/70842529/146251276-6a76fadd-de99-415d-96d4-fa6b8403cf77.jpg)
.

**Comment by Clm-Roig** [comment]
Il y a 2 principaux paramètres sur lesquels on peut jouer ici : 
- L'ordre entre les deux blocs (spécifiques et tous)
- Le bloc ouvert par défaut 

J'imagine que pour que ce soit "plus mis en évidence", il faudrait inverser ces deux choses ? (le bloc "spécifiques" en premier et ouvert par défaut).

**Comment by Clm-Roig** [comment]
@hafidinferno un avis quant à mon précédent message ?

**Comment by urien** [comment]
Salut @Clm-Roig, c'est une bonne solution. Je propose que les tickets qui seront ouverts par @hafidinferno lui soit réservé dans l'immédiat.

**Comment by Clm-Roig** [comment]
Fixed by #462
