### ISSUE TITLE
[DOCUMENT] Display files license

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#302]
Pour les documents les utilisateurs peuvent choisir une licence parmi une liste qui leur est proposée. Il faudrait que la licence retenue apparaisse sur la ligne où le fichier est téléchargeable
![image](https://user-images.githubusercontent.com/1165144/146391345-f007a7e4-e1b1-484c-8570-a8e08186f701.png)
Cela correspond à cette fiche

https://grottocenter.org/ui/documents/25084

**Comment by Clm-Roig** [comment]
Pour info, la licence dans le fichier est bien retournée par l'API et contient les données `name` et `url` que l'on doit utiliser ici.

**Comment by urien** [comment]
Quelque chose de semblable a été développé pour les documents qui sont associés aux cavités
![image](https://user-images.githubusercontent.com/1165144/158033785-c69889c4-76aa-4ce9-8b42-109609f569f8.png)
C'est visible, par exemple ici
https://beta.grottocenter.org/ui/entrances/5655

**Comment by urien** [comment]
Done by Vincent
