### ISSUE TITLE
[ORGANIZATIONS & MASSIFS] Replace caves with entrances

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#303]
Nous avons décidé que les utilisateurs auraient accès aux informations sur les cavités (cave) depuis les entrées (entrance) et que les caves ne seraient pas accessibles via Grottocenter pour éviter les confusions.

Il faut donc remplacer sur les pages des organisations et des massifs, les listes de caves par des listes d'entrances

![image](https://user-images.githubusercontent.com/1165144/146537537-160be07c-113c-477f-9f70-7366eafdefe2.png)

**Comment by bsoufflet** [comment]
EN effet, cette issue est bien car détachée des dev actuel :)
