### ISSUE TITLE
[WELCOME PAGE] start with the map

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#305]
La page d'accueil sera la carte.

**Comment by Clm-Roig** [comment]
Attention, on a déjà l'issue #17 pour ce qui concerne le menu. Est-ce que tu peux éditer ton message là-bas et supprimer ici ce qui concerne le menu s'il te plaît ? Comme ça cette issue se concentre uniquement sur la carte en page d'accueil :slightly_smiling_face:

**Comment by urien** [comment]
A revoir ultérieurement. Un ticket plus précis sur l'organisation de l'accueil devra être réalisé et validé
