### ISSUE TITLE
[ENTRANCE Show] presentation of latitudes and longitudes

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#307]
Après échange au sein de l'association la présentation qui est retenue est la suivante
![image](https://user-images.githubusercontent.com/1165144/146719958-9bc5e09e-698e-4b03-a0ef-d36a77ac43fd.png)

**Comment by bsoufflet** [comment]
@BTHOM @urien : Faut il également afficher quelques par "WGS84" ?

**Comment by urien** [comment]
Oui, pourquoi pas. il faut envisager qu'un convertisseur soit ensuite proposé.

**Comment by BTHOM** [comment]
Oui, cela permet de bien définir le référentiel des coordonnées
