### ISSUE TITLE
[ENTRANCE DETAILS] Addition of a scroll on the left part of the window if all the information is not visible

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#308]
Pour certaines fiches l'ensemble des informations de la fenêtre de gauche ne sont pas visibles. Il faudrait rajouter une barre de défilement
![image](https://user-images.githubusercontent.com/1165144/146720446-94b78cff-b274-4949-b3d9-e1c7fb62de8a.png)

**Comment by bsoufflet** [comment]
Ce problème peut arriver sur un petit écran en mode paysage avec un très long nom de cavité qui s'affiche sur plusieurs lignes.
