### ISSUE TITLE
[DOCUMENT ADD FILE] Don't close the page

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#320]
L'ajout de fichiers aux documents commencent à être utilisé et quand les utilisateurs ont cliqué sur valider... ils ferment la fenêtre. En général cela créé le document, cela enregistre les informations sur la licence du fichier mais le fichier n'est pas téléchargé.

Le fait d’atténuer les couleurs et de mettre une fine bande qui défile n'est pas assez visible, il faudrait un message plus explicite pour indiquer que le fichier est en cours de téléchargement et qu'il ne faut pas fermer la fenêtre.

**Comment by Clm-Roig** [comment]
Voir le composant "Promp" de react-router-dom (que l'on utilise déjà) : https://v5.reactrouter.com/core/api/Prompt

**Comment by Clm-Roig** [comment]
Quel message voudrais-tu @urien ? Sachant que je ne détecte uniquement si l'envoi du formulaire est en cours, indépendamment du fait que ça vienne d'un fichier ou pas. De toute façon, s'il n'y a pas de fichiers ça va très vite et l'utilisateur n'a pas vraiment le temps de quitter la page.

Quelque chose comme : 

`Le document est en train d'être créé. Si vous quittez maintenant, il pourrait contenir des données incomplètes : êtes-vous sûr de vouloir quitter ?`

**Comment by urien** [comment]
Peut être déjà un message quand on valide pour demander de ne pas fermer la fenêtre tant que le fichier n'est pas téléchargé. Puis si on demande à fermer la fenêtre le message que tu proposes.

**Comment by urien** [comment]
Est ce que tu peux en profiter pour passer la taille max des fichiers a 2Go pour les vidéos ?

**Comment by Clm-Roig** [comment]
>tant que le fichier n'est pas téléchargé


Je n'ai pas cette info, je sais juste si ça charge en gros. Je ne peux mettre qu'un seul message pour tout ça. Si tu veux, on peut poursuivre la discussion et tester sur la PR ici : #385

**Comment by urien** [comment]
En fait c'est rajouter une fenetre au milieu de la page quand on clique sur soumettre, jusqu'à ce que la fenêtre se rafraichisse quand la mise à jour est finie. Je suis en train de récupérer un gros fichier pour faire un test

**Comment by Clm-Roig** [comment]
Je vois, je fais ça de suite

**Comment by urien** [comment]
C'est nickel... mais il n'est plus possible d'ouvrir la page de validation des documents. Si c'est un pb indépendant tu peux publier cette issue

**Comment by Clm-Roig** [comment]
C'est indépendant mais très étrange, une autre issue ouep' !
