### ISSUE TITLE
[MASSIF] Massif for users > implementation to meet needs

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#322]
Un massif est une unité géographique qui peut être défini par un polygone sur une carte.
Il peut être associé à des documents, à des organisations et à des cavités
Il est possible d'avoir des massifs imbriqués correspondant à des niveau de zoom différent
`par exemple Alpes > Chartreuse > Grand Som > Vallon des Eparres`
Mais il également possible d'avoir des massifs correspondant à d'autres découpages
`par exemple le périmètre du parc Naturel des Grand Causses ou le bassin Hyrdaulogique de la source de Miolène `
Pour chacun de ces massifs il faut qu'une procédure automatique, utilisant les fonctionnalités de PostGis, associent les cavités qui se trouve dans le périmètre défini par le polygone du massif

**Comment by Clm-Roig** [comment]
Ceci concerne l'API et fait doublon avec cette issue je crois : https://github.com/GrottoCenter/Grottocenter3/issues/411

**Comment by urien** [comment]
Ok je ferme
