### ISSUE TITLE
[DOCUMENT AUTOR PUBLISHER... MASSIF ORGANIZATION] Delete

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#326]
Pour l'ensemble des entités

- un bouton 'supprimer' est visible pour les administrateurs et les modérateurs
- un bouton 'alerter' est visible pour les autres utilisateurs

Le bouton 'alerter' ouvre un lien vers https://en.wikicaves.org/contact

Le bouton 'supprimer' offre deux possibilité

1. supprimer l'entité (passer le champ isDeleted à true dans les tables où l'entité apparait)
2.  fusionner l'entité avec une autre (passer le champ isDeleted à true dans la table de l'entité et remplacer l'id de l'entité supprimée par celle avec laquelle elle est fusionnée dans les autres tables)

ATTENTION : pour les personnes il ne doit pas être possible de supprimer une personne ayant un compte, seulement des personnes qui sont des auteurs

**Comment by Clm-Roig** [comment]
> Si on souhaite effectivement complètement supprimer un objet on peut le fusionner avec un objet "organisation inexistante" (par exemple) et cet objet contiendra des informations donnant à l'utilisateur des informations lui expliquant qu'il a demandé à visualiser un objet qui a été supprimé car il n'existait pas.

Ce n'est pas une bonne idée je pense. La gestion des données inexistantes est bien plus facile quand un objet n'existe "réellement" plus pour l'API (donc champ "isDeleted" à true mais ça, le client s'en fiche : il reçoit juste une erreur 404). 
Les données doivent être uniques et fidèles à la réalité au maximum. Le reste, c'est une question d'interface utilisateur selon moi.

PS : cette issue doit être divisée en 2 (client et API), elle regroupe pas mal d'informations différentes.

**Comment by urien** [comment]
La difficulté c'est que nous avons vocation a fournir des url permanente pour tous les objets, afin que les applications qui nous utilisent et qui ont stocké l'id d'un objet, aient toujours une réponse (200) pour tous les objets qui ont existé à un moment donné.
L'exemple pour illustrer cette problématique, c'est Karst 3D qui associe les topographies à une cavité qui est connue par Karst3D par son id dans Grottocenter. cela permet à l'application de créer un lien vers la page sur Grottocenter et de récupérer des données actualisées. Il faut que ce lien fonctionne toujours, même si l'objet a été supprimé. La seule bonne raison de supprimer un objet c'est qu'il y a un doublon. Les faux objets, qui ne correspondent pas à des doublons, résultent de tests ou de malveillance, ce sont des situations assez rares que nous pouvons traiter comme les doublons

**Comment by Clm-Roig** [comment]
> Il faut que ce lien fonctionne toujours, même si l'objet a été supprimé. 

Une erreur 404 est un lien qui fonctionne toujours, libre aux utilisateurs (y compris Karst 3D) de traiter cette information comme ils le veulent. Fin bref, je joue sur les mots, je m'égare 😅 

Par contre, pour résumer, je vois deux cas qui se dessinent et qu'on doit (et qu'on peut) traiter correctement (corrige-moi si je me trompe) : 

> Les faux objets, qui ne correspondent pas à des doublons, résultent de tests ou de malveillance 

:x: Suppression pure et simple ? On peut même ne pas passer `isDeleted` à true normalement dans ce cas là, c'est poubelle directement.

> Doublon (disons id 1 qui fusionne avec id 2, il ne reste plus qu'id 2)

Suppression de l'id1, avec passage de `isDeleted` à true... Mais on garde en mémoire le fait qu'il a été fusionné avec l'id 2. Il faut donc ajouter un champ ou une table pour référencer toutes les fusions qui ont eu lieu.

Conséquence :  quand on fait fait GET /1, on obtient une réponse 301 ("[Moved Permanently](https://fr.wikipedia.org/wiki/HTTP_301)") de la part de l'API qui indique qu'il faut désormais l'id 2. 

Et donc la fusion avec une entité "inexistante" n'est plus nécessaire non ? Pour revenir à mon premier commentaire dans ce message, le 404 EST une entité inexistante par essence, ça existe déjà, pas besoin de recréer ça en base de données.

**Comment by vmarseguerra** [comment]
Compete with https://github.com/GrottoCenter/grottocenter-front/pull/985, https://github.com/GrottoCenter/grottocenter-front/pull/989, https://github.com/GrottoCenter/grottocenter-front/pull/990, https://github.com/GrottoCenter/grottocenter-front/pull/991
