### ISSUE TITLE
[ENTRANCE CREATE] Add translations and change network by cave in the search module

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#334]
**Is your feature request related to a problem? Please describe.**
Quelques ajustements sur la création de cavités : 
- Ajouter les traductions (chaînes de caractères traduisibles) 
- Revoir la tournure de phrase "choix d'une cavité existante VS nouvelle cavité" :

> **Linked to an existing network**
> **First entrance of the cave (on Grottocenter)**

à remplacer par 

> **Linked to an existing cave or network**
> **First entrance of the cave (on Grottocenter)**

- Chercher parmi toutes les caves au lieu des networks

**Comment by Clm-Roig** [comment]
> **Is your feature request related to a problem? Please describe.** Quelques ajustements sur la création de cavités :
> 
>     * Mettre en place la localisation (chaînes de caractères traduisibles)
> 
>     * Revoir quelques tournures de phrases (choix d'une cavité existante VS nouvelle cavité) :
> 
> 
> > **Linked to an existing network**
> > **First entrance of the cave (on Grottocenter)**
> 
> à remplacer par
> 
> > **Linked to an existing cave to create a new network**
> > **First entrance of the cave (on Grottocenter)**
> 
>     * Chercher parmi toutes les caves au lieu des networks

**Comment by Clm-Roig** [comment]
>     Chercher parmi toutes les caves au lieu des networks

Je viens de regarder, en fait c'est déjà le cas. Faut juste changer le label.
