### ISSUE TITLE
 [DOCUMENT] Add place information

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-front#335]
## Describe your problem
Currently, a document has only a `region` attribute to localize it somewhere. This is inherited from the BBS data. We want to add more information about the document place (if it's related to one). And no longer allow you to fill in BBS regions that no longer correspond to existing administrative entities

## Solution existante
https://github.com/GrottoCenter/grottocenter-api/pull/1160

### Fonctionnement souhaité

Lorsqu'on créé ou qu'on édite un document, à la place du champ région (qui est supprimé) : 
- afficher un champ pays qui permet de sélectionner un pays figurant dans la table t_country. Cette sélection est optionnelle
- La sélection d'un pays entraine l'affichage d'un champ **Entité administrative de niveau 1** qui offre la possibilité de choisir dans la table iso_3166_2 parmi les entités qui ont pour parent un id_country correspondant à celui qui vient d'être choisi. Ce choix est optionnel
- La sélection d'une entité pour Admin1 conduit a afficher un champ **Entité administrative de niveau 2** qui offre la possibilité de choisir dans la table iso_3166_2 parmi les entités qui ont comme parent l'id correspondant a celui qui vient d'être choisi.

### A voir
- Il faudrait modifier le module de recherche avancé en ajoutant la recherche par pays / admin1 / admin2
- Il y a des champs (entourés en rouge qui devraient être mis dans une catégorie à parti : ce sont des données historiques du BBS qui ne sont plus alimentées et il faudrait voir s'il est pertinent de faire une recherche par nom et par pseudo
![image](https://github.com/GrottoCenter/grottocenter-front/assets/1165144/e1b44fd6-8096-4134-9410-5ff928d77a5e)

- il faudrait mettre à jour le module d'import csv pour que le champ pays qui est alimenté par le code iso 2 chiffres soient bien importé

**Comment by urien** [comment]
La mise en place de cette fonctionnalité nécessite de faire des modifications dans les pages  de création, édition, visualisation et recherche avancée.
Il faudrait regarder quelle est l'api qui fourni les services attendus. Je me demande si ce n'est pas plutot https://developers.google.com/maps/documentation/geocoding

Pour les documents on utiliserait le pays et la région, éventuellement le département (soit deux ou trois champs) la possibilité de saisir une région ou un département dans un champ texte ne me semble pas utile à ce niveau là, la base de Google doit être complete.
cela deviendra pertinent au niveau de la commune ou du lieu dit
Le découpage pourrait reprendre ce qui est utilisé dans les normes ISO 
référence à compléter
https://fr.wikipedia.org/wiki/ISO_3166-2
https://fr.wikipedia.org/wiki/Liste_des_subdivisions_par_pays
Les entités administratives sont différentes selon les pays  on utilise des niveaux
Niveau 1 : région en France
Niveau 2 : département en France
Au dela du niveau 2 cela devient difficile à gérer, je propose d'en rester là (en France la commune correspond au niveau 5 car avant il y a l'arrondissement et l'intercommunalité, mais dans d'autres pays la commune correspond au niveau 3 ou 4)

**Comment by urien** [comment]
Done by Vincent
