### ISSUE TITLE
[ENTRANCE PAGE] Show locations

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#34]
Les données viennent de la table t_location
Les informations seront placées dans un cadre semblable a celui qui est utilisé pour afficher les descriptions.
Ce cadre sera placé au-dessus de la description

**Comment by urien** [comment]
Sur la V2 de Grottocenter cela ressemble à cela

![image](https://user-images.githubusercontent.com/1165144/138932721-d3f57197-5145-4252-8140-b4ac10b5f644.png)

**Comment by Clm-Roig** [comment]
L'API est prête et en production. L'attribut à utiliser est `locations`.
