### ISSUE TITLE
[MASSIF] Create / edit

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#340]
La création et l'édition d'un massif va se faire avec un stepper comme pour les documents ou les cavités.
Premier étape

- Nom (obligatoire)
- Description**s** (optionnelle) : titre, description, langue de la description

Seconde étape

- création / édition du polygone sur la carte

Troisième étape

- Champs qui seront définis lors des échanges avec les utilisateurs

Validation

- Affichage de l'ensemble des éléments qui ont été retenus
- Indication de la licence qui va s'appliquer au contenu

**Comment by lageta** [comment]
Lors de la création d'un massif, la création d'un polygone n'est pas obligatoire ?

**Comment by urien** [comment]
Il me semble préférable de le rendre obligatoire, idem lors de l'édition quand il n'y en a pas. Quel est ton avis @bsoufflet ?

**Comment by lageta** [comment]
Autre question qui a le droit de créer/éditer un massif ? Tous les utilisateurs ? Seulement les admins ? Les utilisateurs avec une condition spécifique ?

**Comment by urien** [comment]
Tous les utilisateurs (connectés)

**Comment by bsoufflet** [comment]
![image](https://user-images.githubusercontent.com/985903/164114254-f8ff9de3-6829-4bf9-8b29-843060fdb66d.png)
Dans le modèle de BDD ce n'est pas obligatoire. Cependant, cela me semble judicieux comme le propose @urien de le rendre obligatoire coté front en imposant la saisie lors de la création et de l'édition.

**Comment by lageta** [comment]
![image](https://user-images.githubusercontent.com/74241345/167016469-66b2233d-c7f9-414f-8c1a-7635f785896c.png)
![image](https://user-images.githubusercontent.com/74241345/167016647-1e281d3f-0ad1-4353-90d2-8c5d098f859c.png)

@urien  @Clm-Roig  @bsoufflet 
Voilà je poste des designs pour valider avec vous les schémas et surtout les labels pour les traductions. Pour la création de massif on aurait que 2 parties pour l'instant. Une 3ème concernera des liens plus développées entre les massifs et les autres entités de grottocenter, elle arrivera plus tard j'essaie de créer un composant qui pourra nous permettre de rechercher et sélectionner des documents (si cela existe déjà sur grottocenter faites le moi savoir !)

Pour l'instant mon idée sur ce composant c'est de faire un find-all documents et de permettre à l'utilisateur d'en sélectionner une liste à associer au massif.

**Comment by urien** [comment]
C'est bien. Pour les documents, partir d'une recherche est une bonne idée. On va rechercher des documents qui parlent du massif

**Comment by bsoufflet** [comment]
@urien @lageta : Comme je le proposais dans une autre discussion, il ne me semble pas pertinant de perdre du temps de dev à vouloir gérer manuellement des relations entre des massifs et des documents. Pour moi il faut faire cela de manière automatique : 
- on a des relations entre des documents et des cavités
- on connait la position géographique des cavités et l'emprise des massifs
- > donc via une requête SQL on peut avoir les documents du massif et inversement :) 

Autant consacrer le temps de dev à faire cela plutot que des interfaces utilisateurs pour gérer manuellement des relations (qui seront toujours incomplètes en plus...)
