### ISSUE TITLE
 [ORGANISATION] Create / Edit

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#341]
La création et l'édition des organisation se fera à travers un stepper comme pour les cavités et pour les documents.

Étape 1

    Nom (obligatoire)
    Est partenaire (pour les administrateurs)
    Descriptions (Optionnel) composé d'un titre, d'un texte et de la langue utilisée.

Étape 2 (tous champs optionnels)

    Adresse 1
    Adresse 2
    Code postal
    Ville
    Pays
    Téléphone
    mél
    url

Étape 3 (optionnelle)

    localisation sur la carte

Étape 4 (optionnelle)

    logo de l'organisation
    Attention ce logo sera utilisé sur la page d'accueil pour les partenaires.

Étape 5 (optionnelle)

    Autres informations qui seront déterminées en fonction des demandes des utilisateurs.

Validation

    Affichage des informations saisies
    Information sur les licences qui vont s'appliquer aux données fournies
    Confirmation et fin de saisie

**Comment by lageta** [comment]
![image](https://user-images.githubusercontent.com/74241345/168148052-6aa03732-8dc3-4f36-b258-1c5a3eb52e37.png)

J'ai relevé quelques incohérences avec la base de données : 

- Il est question de deux adresses mais un seul champs est dans la base données 
- On parle de description avec un titre et un texte mais dans le modèle de données les grottos n'ont pas de descriptions. Est-ce que c'est le custom message de la BD ? 
- Les champs village, county, région et yearOfBirth ne sont pas utilisés ?

**Comment by lageta** [comment]
Il me faudrait plus d'informations sur les licenses également. Concrètement qu'est ce que je peux afficher dans la partie "Validation".

**Comment by urien** [comment]
Effectivement, dans l'idéal il aurait fallu deux champs adresse et il aurait fallu associer les organisations à la table des descriptions.
Je propose de rester sur une ligne d'adresse et d'utiliser le champ custom message.
Les champs village,... sont des champs qui étaient présents dans la base de la version précedante de Grottocenter. Dans l'immédiat on ne les supprime pas, on verra si on s'en sert ou pas ultérieurement.
Comme texte je propose
The selected licenses will apply to your contribution
Puis ce que l'on utilise comme texte pour décrire les licences dans la barre de menu
![image](https://user-images.githubusercontent.com/1165144/168219555-7a31d3e2-cf4b-4f1d-97d6-1d2537d41374.png)
et
![image](https://user-images.githubusercontent.com/1165144/168219635-325f76bb-ed9f-45ee-b0c2-bdef9f50723a.png)
