### ISSUE TITLE
[PERSON] Edit

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#342]
L'édition de la page d'une personne est possible pour la personne elle même ou par un administrateur.

L'édition se fait à travers un formulaire à plusieurs étapes, avec Steppers.

### Étape 1 - Infos de base

- Mail 
- Mot de passe
_- (Voir les contrôles à mettre en place sur le mail et sur le mot de passe)_
- Nom
- Prénom
- Surnom

### Étape 2 - Liens

Autres informations à déterminer comme l'appartenance à une organisation.

### Étape 3 - Validation

- Récapitulatif des données 
- Mise en valeur des données qui seront publiquement accessibles
- Information indiquant que les données librement accessibles sont placées sous licence ODBL

**Comment by Clm-Roig** [comment]
Je me suis permis de mettre un peu en page ton message @urien.

> ### Étape 1 - Infos de base
> 
>     * Mail
> 
>     * Mot de passe
>       _- (Voir les contrôles à mettre en place sur le mail et sur le mot de passe)_
> 

Selon moi, on devrait dissocier l'édition d'un compte et l'édition d'une fiche d'auteur. Ce sont 2 fonctionnalités différentes, avec des niveaux de visibilités et de sécurité distincts.

Dans le premier cas, je dirais que seul l'utilisateur et les administrateurs peut s'éditer. Qui plus est, le mot de passe et le mail ne devraient être changés que par l'utilisateur. 

Dans le second cas, il n'y a pas d'édition de mail et de mot de passe et tout le monde peut le faire (?), corrige-moi si je me trompe.

**Comment by urien** [comment]
Je pense que l'édition de la fiche d'un auteur n'est sans doute pas nécessaire. C'est pourquoi je n'ai envisagé qu'une alternative (ton premier cas). Au pire les administrateurs pourront le faire si, à la fin du merge de tous les doublons, on découvre une faute d'orthographe

**Comment by lageta** [comment]
En plus des infos de bases, il est possible de modifier les documents, les organisations, les cavités explorées ? Pour les organisations on peut simplement se "désinscrire" d'une organisation où l'on peut aussi s'en attribuer une ? (idem pour les documents et les cavités)

**Comment by urien** [comment]
Toute personne enregistrée peut modifier document organisation, massif ou cavité.
Effectivement lors de l'édition de sa fiche une personne doit pouvoir modifier la liste des organisations dont il fait partie. ou la liste des cavités qu'il a visité (cela me semble être plus simple de le faire depuis la fiche d'une cavité plutôt qu'ici)
Pour les documents la modification va se faire depuis la fiche du document

**Comment by lageta** [comment]
Dans éditer la personne on aurait une liste des documents/cavités où chaque élément redirige vers une page pour éditer ce document/cavité  ? 
On peut alors envisager des actions rapides dans cette liste comme supprimer un document sinon cette liste sera essentiellement de la redirection… Pour les cavités il y a une variable isPublic, on peut aussi imaginer pouvoir rendre facilement une cavité explorée public/privé

**Comment by urien** [comment]
L'édition des documents, des cavités, des organisations, des massifs est possible par tout le monde depuis la page de ces entités

**Comment by urien** [comment]
Donc sur la page des personnes il n'y aura qu'il liste de liens vers les entités liées.
Il faut réfléchir à la manière de gérer ces listes qui peuvent être très volumineuses
