### ISSUE TITLE
[ORGANIZATION] View

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#345]
La page de l'organisation doit permettre de visualiser :

- Son nom et la langue de son nom
- Ses descriptions (titres, corps et langue)
- Une carte avec sa localisation si elle existe
- Les documents que l'organisation a édité
- Les personnes qui sont membres de l'organisation
- Les cavités que l'organisation a exploré
- D'autres champs qui seront déterminés à partir des demandes des utilisateurs

**Comment by VivienLvr** [comment]
@urien Les organisations ont-elles des entrées parrainées ou des réseaux parrainés ? C'était affiché sur la page organisation déjà en place mais vous ne l'avez pas mentionné et je ne trouve pas d'organisation ayant des entrées ou réseaux parrainés.

**Comment by urien** [comment]
C'est quelque chose qu'on avait dans la V2 de Grottocenter.
Ce n'est pas essentiel et cela demanderait du dev côté back car seuls les admins peuvent réaliser cette association.
Je propose de supprimer cet affichage et de le remettre en place ultérieurement dans un développement spécifique

**Comment by VivienLvr** [comment]
D'accord je l'enlèverai de la page pour l'instant dans ce cas.
