### ISSUE TITLE
[MASSIF / ENTRANCE / ORGANIZATION / PERSON] delete

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#347]
Un bouton (croix) placé en bas à droite de la fenêtre est uniquement présent si la personne connectée a le statut d'administrateur. Le clic sur ce bouton génère le processus décrit coté Serveur.

**Comment by Clm-Roig** [comment]
> Le clic sur ce bouton génère le processus décrit coté Serveur.

J'imagine que tu parles de https://github.com/GrottoCenter/Grottocenter3/issues/733 ? Auquel cas, cette issue ne décrit pas le processus de suppression mais explicite seulement une modification dans la BD. Il faut peut-être retravailler l'issue côté serveur pour qu'elle explique non seulement la modif en BD mais aussi le processus de suppression.

**Comment by urien** [comment]
Je pensais faire deux tickets coté Back : celui que j'ai fait pour décrire les modifications sur la DB et faire un second ticket, qui décrive l'api et son fonctionnement. Je vais faire ce second ticket dès que possible

**Comment by Clm-Roig** [comment]
Ok parfait !

**Comment by urien** [comment]
Un seul ticket pour delete https://github.com/GrottoCenter/grottocenter-front/issues/326

**Comment by urien** [comment]
> Un bouton (croix) placé en bas à droite de la fenêtre est uniquement présent si la personne connectée a le statut d'administrateur. Le clic sur ce bouton génère le processus décrit coté Serveur.

 les

**Comment by urien** [comment]
see https://github.com/GrottoCenter/grottocenter-front/issues/326
