### ISSUE TITLE
[ENTRANCE PAGE] Show histories

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#35]
Il s'agit d'afficher les données issues de t_history
L'affichage se fera dans un cadre du même type que la description
Ce cadre prendra place après le cadre "Rigging"

**Comment by Clm-Roig** [comment]
L'API est prête et en production. L'attribut à utiliser est `histories`.
Un `history` a une structure très proche d'une `description` si je me souviens bien (auteur, titre et body).

**Comment by ClemRz** [comment]
> L'attribut à utiliser est `histories`.

Merci @Clm-Roig !
Ne serait-il pas plus correcte que ce soit `history` d'un point de vue de l'Anglais?

**Comment by Clm-Roig** [comment]
Nop, il y a plusieurs history donc c'est une collection donc je mets au pluriel 🙂

**Comment by ClemRz** [comment]
Merci @Clm-Roig !
Je vais commencer a travailler sur ce ticket.
