### ISSUE TITLE
[DUPLICATE TOOLS] After submission the file to be merged remains

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#356]
**Describe the bug**
Quand on clique sur le bouton "soumettre", on arrive sur une page avec un bouton "Go Back".
Il serait préférable d'arriver directement sur le tableau avec les fichiers à valider. Cela ferait un clic de moins.

Quand on est redirigé sur le tableau des doublons, après avoir soumis, la fiche qu'on vient de soumettre est encore présente. Il n'est pas possible de la sélectionner pour la supprimer. La seule solution est de la sélectionner pour la traiter puis d'indiquer que ce n'est pas un doublon.

**Comment by urien** [comment]
A la fin de ma série, j'ai deux documents que je ne peux pas traiter

**Comment by Clm-Roig** [comment]
Je n'arrive pas à reproduire ce problème sur ma machine. Je suppose que ce qui doit arriver, c'est qu'une erreur apparaît quand tu soumets et donc la suppression du doublon n'a pas lieu. Puis tu es redirigé vers le tableau sans être informé de l'erreur. 

Concernant le bouton "Go Back", je pense que c'est la même chose. Chez moi, quand la soumission réussit, je suis correctement redirigé vers le tableau. Tu dois avoir une erreur quelque part...

**Comment by Clm-Roig** [comment]
Ça devrait marcher désormais, tu pourras fermer l'issue après tes tests @urien stp ?

**Comment by urien** [comment]
Résolu
