### ISSUE TITLE
[DUPLICATE TOOLS] Language management problem

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#357]
**Describe the bug**
Quand on est dans l'interface qui permet de fusionner deux fiches, le document présent dans la base apparaît comme ayant une première langue indéfinie. Il est possible de sélectionner la langue venant du document importé et de supprimer la langue associé au document déjà dans la base.
Mais après fusion, si on va voir la fiche du document la langue du document apparait toujours comme Unknow.

**Comment by Clm-Roig** [comment]
Je n'arrive pas à reproduire sur ma machine... Le document en base a bien une langue définie chez moi, je peux la sélectionner ou la remplacer par celle du nouveau document comme je veux.

**Comment by urien** [comment]
Je vais faire un test avec le fichier 
[test1.csv](https://github.com/GrottoCenter/grottocenter-front/files/8419824/test1.csv)
Je mets à ta disposition le fichier 
[test2.csv](https://github.com/GrottoCenter/grottocenter-front/files/8419829/test2.csv)
pour faire le test de ton côté.
L'utilisation de ces fichiers permet de tester également ce qu'il se passe après la validation d'une fusion.

1. J'importe mon fichier CSV
![image](https://user-images.githubusercontent.com/1165144/161795535-5b0b18c1-d120-4dd5-a97b-db9bc639a3db.png)


2. Dans l'outil de gestion des doublons je sélectionne le document que je viens de rajouter
3. Je clique sur Take all à gauche, je clique sur document parents et sur language à droite. Et je supprime la langue 1 00 qui est la langue du document existant dans la base
![image](https://user-images.githubusercontent.com/1165144/161796564-4f3619bd-15fa-465c-8ca1-eb14fc54ea4b.png)


Et là magie, je retourne sur le tableau avec la liste des doublons... pas de bug à la validation

Mais le document pour lequel je viens de déclarer la langue Française est en langue inconnue

![image](https://user-images.githubusercontent.com/1165144/161796965-abb5b36b-0c17-4f5d-9dcc-c28ffe8a8f2b.png)

**Comment by Clm-Roig** [comment]
J'ai trouvé. Le problème ne vient pas de l'outil de gestion des doublons. Le problème vient juste de la page "documents" qui n'affiche pas la langue du tout. Voilà ce que j'ai en production quand j'arrive sur la page : 

![image](https://user-images.githubusercontent.com/20704943/161935374-6ebbfd74-e527-446a-b1f0-d25204cc64cf.png)

Le language "fra" est bien renvoyé par le serveur (et il l'est aussi en BD). J'ouvre une issue (#380) pour résoudre ce problème d'affichage et je ferme celle-ci.
