### ISSUE TITLE
[ENTRANCE PAGE] Show various informations

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#37]
Pour avoir les informations qui étaient disponibles dans la V2 il convient de donner accès aux informations suivantes.
Ces informations seront à mettre en place sous la carte en complément des informations figurant déjà

![image](https://user-images.githubusercontent.com/1165144/138730650-00b4e9b2-d26a-469a-aade-9fbe43e91314.png)

- [x] Température (t_cave:temperature)
- [x] Présence ou non de siphon (t_cave:isDiving)
- [x] Date de découverte (t_entrance:discoveryYear)
- [x] Temps d'acces calculé sur la moyenne des (t_comment:E_t_trail) il existe un picto pour ce champ
- [x] Temps sous-terre calculé sur la moyenne des (t_comment:E_t_underground). Il existe un picto pour ce champ
- [x] Altitude : (t_entrance:altitude)

Problème de la sensibilité de l'entrée déplacé ici =>  #299

**Comment by Clm-Roig** [comment]
J'ai fait les modifs pour quasiment tout (PR #298). Maxime l'avait déjà fait, il fallait juste modifier les chemins vers les données.

Reste le problème de la sensibilité : j'ai ouvert une issue dédiée à ce problème (#299), j'ai quelques questions à poser pour des cas particuliers
