### ISSUE TITLE
[AUTH] Password change

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#38]
Pour finaliser le module d'authentification
Il faut créer une page accessible via le lien qui est dans le mel qu'on reçoit quand on demande à mettre à jour son mot de passe
Cette page permettra de créer un nouveau mot de passe.
Il conviendra également de finaliser la localisation

**Comment by Clm-Roig** [comment]
The page will be located at : https://beta.grottocenter.org/ui/changePassword?token=123456789. The link (including the token) is obtained via email when an user requests a password change.

The token must be extracted from the URL and passed alongside the new password to the route **PATCH api.grottocenter.org/api/v1/account/password**. Here is the HTTP body structure of this route:

```json
{
  "password": "my_new_secure_password",
  "token": 123456789
}
```

**Comment by Clm-Roig** [comment]
>  Il conviendra également de finaliser la localisation

Tu peux ouvrir une nouvelle issue pour ça, avec plus d'infos @urien stp ?
