### ISSUE TITLE
[DOCUMENT] Validation don't work

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#386]
**Describe the bug**
Lorsqu'on appelle la page https://grottocenter.org/ui/documents/validation
elle demeure blanche.

J'ai l'impression que c'est lié à la mise à jour de certains plugin
`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20part2b%2C%20part2t%2C%20part1%2C%20scope%2C%20type%2C%20refName%2C%20comment%2C%20isPrefered%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    V scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
[react-dom.production.min.js:216:199](webpack-internal:///node_modules/react-dom/cjs/react-dom.production.min.js)
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    V scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    render index.tsx:139
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    V scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
[react-dom.production.min.js:216:199](webpack-internal:///node_modules/react-dom/cjs/react-dom.production.min.js)
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    render index.tsx:139
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    V scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
[react-dom.production.min.js:216:199](webpack-internal:///node_modules/react-dom/cjs/react-dom.production.min.js)
Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    render index.tsx:139
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    V scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12`

**Comment by Clm-Roig** [comment]
Fixed by #388
