### ISSUE TITLE
[DUPLICATE] Imported files should be merged together

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#390]
**Describe the bug**
J'ai importé le fichier suivant
[test2.csv](https://github.com/GrottoCenter/grottocenter-front/files/8429819/test2.csv)
Normalement tous les fichiers sont déjà dans la base. Au départ il m'a prévenu que 265 lignes étaient des doublons, puis après l'import que 305 étaient des doublons (les chiffres ne sont peut être pas exacts mais sont différents).

Dans le module permettant de fusionner les documents, celui-ci me propose de merger entre eux les documents qui ont été importés. Les deux ont des documents parents alors que ceux qui sont en base n'en ont pas. Il n'est pas possible de les supprimer. 

Dans l'immédiat je laisse ainsi pour permettre de faire des tests.

**Comment by urien** [comment]
Je viens d'utiliser l'outil d'import via csv pour des entrées. Elles se retrouvent dans l'outil de gestion des doublons. J'ai pu supprimer la première ligne mais ce n'est pas possible pour les suivantes

**Comment by Clm-Roig** [comment]
Ça devrait marcher désormais, tu pourras fermer l'issue après tes tests @urien stp ?

**Comment by urien** [comment]
Résolu
