### ISSUE TITLE
[CSV IMPORT CAVE] error while reviewing data

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#392]
Avec le fichier ci-dessous le clic sur le bouton suivant pour arriver à la revue des données, conduit à une page blanche
[cavetest.csv](https://github.com/GrottoCenter/Grottocenter3/files/8453647/cavetest.csv)

**Comment by Clm-Roig** [comment]
C'est un problème côté front, je transfère là-bas (et je résous rapidement).

**Comment by Clm-Roig** [comment]
Le CSV n'est pas bon, il y a un saut de ligne en trop juste avant la description. Voici le fichier corrigé : 
[cavetest.csv](https://github.com/GrottoCenter/grottocenter-front/files/8456449/cavetest.csv)

Il y a aussi un petit problème dans le code, je m'en occupe.

**Comment by Clm-Roig** [comment]
En fait il n'y a pas de problème dans le code. Il y a un deuxième souci dans le CSV. 

A la fin, il y a une description en italien ("Il tratto che...") qui est censé être la dernière colonne. Mais juste après, on a une description supplémentaire en français ("Les premiers -100m...") qui n'est pas attendu et cause le crash. 

J'ai supprimé cette 2ème description et l'import s'est bien passé. Je ferme pour le moment, je suis sur Slack ce matin si besoin.

**Comment by urien** [comment]
Ok, merci.
Désolé pour ces erreurs.
Je refais des tests
