### ISSUE TITLE
[ARCHITECTURE] Clean folder structure

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-front#393]
### Discussed in https://github.com/GrottoCenter/grottocenter-front/discussions/350

<div type='discussions-op-text'>

<sup>Originally posted by **Clm-Roig** March 24, 2022</sup>
Actuellement, on a l'arborescence suivante : 
![image](https://user-images.githubusercontent.com/20704943/159918494-5ab8e994-6a63-46b6-8b7d-cdb7ca5a6f20.png)

Ainsi que la page wiki suivante : 
https://github.com/GrottoCenter/grottocenter-front/wiki/Development-guide

Ce n'est pas trop homogène et plusieurs développeurs se sont succédés avec des visions de React différentes. Je pense notamment avec la notion de smart et dumb composants qui n'est plus vraiment d'actualité dans React désormais.

Voici mes suggestions pour nettoyer / repenser tout ça : 
- `components/admin` n'a pas lieu d'être, les composants étant des briques simples réutilisables : ce n'est pas le cas ici. Il s'agit d'un vieux bout de code qui n'a jamais été utilisé de toute façon : à supprimer. 
- `components/homepage` devrait être migrer dans `pages/homepage`. Le dossier `advancedSearch` irait dans `components/appli`.
- `features` est synonyme de `components/appli` selon moi. Ce sont des composants métiers complexes, propres à Grottocenter dans les deux cas. A déplacer.
- `containers` est un relicat de l'ancienne façon de coder du React. Un jour il faudra migrer le code vers ce qui se fait actuellement (composant fonctionnel pur). Pour le moment on garde mais on ne développe plus rien dedans.

Au final on se retrouverait avec : 
- components 
    - appli
    - common 
    (et rien d'autre)
- containers (déprécié, à migrer un jour)
- pages

J'attends vos avis :slightly_smiling_face: </div>

**Comment by urien** [comment]
Cela me semble bien. Merci pour cette proposition

**Comment by Clm-Roig** [comment]
Je me suis permis de me lancer là-dans après discussion et approbation de Benjamin et Clément comme expliqué ici => https://github.com/GrottoCenter/grottocenter-front/discussions/350
