### ISSUE TITLE
[QUICK SEARCH] multiple results without url

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#395]
dans la recherche rapide on obtient plusieurs fois le même résultat mais seul le dernier a un lien vers la fiche correspondante
![image](https://user-images.githubusercontent.com/1165144/162680602-61085e84-ff71-411c-aa46-2b40cf2d9a4c.png)

**Comment by Clm-Roig** [comment]
Les deux premiers résultats sont des "caves", le 3ème est une "entrance".  Mon hypothèse est donc que la redirection vers les caves ne fonctionnent pas.

**Comment by urien** [comment]
La solution sera de supprimer la recherche sur les caves et de la remplacer, éventuellement, par une recherche sur les réseaux

**Comment by Clm-Roig** [comment]
On n'a pas encore de page "networks" pour rediriger quand on clique dessus... 
2 solutions : 
- on garde la recherche sur les "caves" et je fixe le bug qui empêchait la redirection (c'est déjà fait) 
- on supprime la recherche sur les "caves"

**Comment by urien** [comment]
Plutot supprimer la recherche sur les caves. On se retrouve avec deux fois la même référence sans savoir a quoi correspond chacune d'elles
