### ISSUE TITLE
Create script to update translations

### ISSUE THREAD

**Issue by maximenathan** [GrottoCenter/grottocenter-front#4]
Create a script to update translations from transifex.
Move translations from outside the `web-app` package

**Comment by Clm-Roig** [comment]
See #24 too => we should use the Transifex v3 API now

**Comment by Clm-Roig** [comment]
@urien est-ce que tu peux me donner des droits d'administration sur Transifex pour que je m'occupe de ça s'il te plaît ? J'ai besoin d'accéder aux paramètres de l'organisation "Wikicaves".

**Comment by urien** [comment]
Je viens de le faire

Le mar. 16 nov. 2021 à 15:32, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
J'ai configuré Transifex pour pouvoir faire des [PR de traduction](https://github.com/GrottoCenter/grottocenter-front/pulls).
J'ai mis à jour la page wiki qui explique tout cela : https://github.com/GrottoCenter/grottocenter-front/wiki/Translation-workflow

J'attends de voir comment ça fonctionne sur plusieurs jours / semaines pour mettre à jour les instructions pour les développeurs (du genre : faut-il modifier dans Transifex ? faut-il modifier les fichiers de trad quand on PR ? comment sont gérés les conflits ? etc)

**Comment by bsoufflet** [comment]
Merci pour ce boulot @Clm-Roig :)

**Comment by bsoufflet** [comment]
> Merci pour ce boulot @Clm-Roig :)

Du coup il faut retirer la partie "grunt transifex" de la page wiki non ?

**Comment by urien** [comment]
Merci,

C'est super

Le mer. 17 nov. 2021 à 11:09, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
> Du coup il faut retirer la partie "grunt transifex" de la page wiki non ?
 
C'est fait, merci ! Je réécrirai certaines parties du wiki quand j'aurai trouvé le workflow le plus simple et efficace, d'ici quelques jours / semaines.

**Comment by Clm-Roig** [comment]
J'ai réécrit la page du wiki, c'est tout bon :slightly_smiling_face: Transifex écoute le fichier `en.json`. Au moindre push sur develop, les nouvelles clés de traduction demandées par le développeur sont récupérées automatiquement. 

Il ne reste plus qu'à traduire sur Transifex puis, toutes les 6h je crois, Transifex vérifier si une langue est arrivée à 100% de traduction. Si oui, il fait une Pull Request. 

On peut aussi demander de forcer des Pull Request manuellement en indiquant un pourcentage à partir duquel une langue est poussée vers le répo.

**Comment by urien** [comment]
Une bonne chose de faite,
Je me demande s'il n'y a pas un pb sur le roumain
[image: image.png]
Normalement il est traduit en grande partie et la traduction n'apparait pas



Le mer. 17 nov. 2021 à 15:27, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
Aucune traduction n'a été mise à jour encore, je finissais de tout peaufiner manuellement jusqu'à maintenant. Je vais forcer Transifex à nous soumettre les dernières traductions de ce pas !
