### ISSUE TITLE
[ENTRANCE PAGE] Creation / editing of basic information

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#40]
La création / L'édition d'une entrée se déroule selon un processus semblable a celui qui a été mis en place pour les documents.
Proposition d'étapes

1- Nom de la cavité et coordonnées > La présence de coordonnées donne access aux champs Pays / région / département /  / commune / Lieu dit qui seront préremplis en utilisant le travail réalisé par des étudiants. Ces valeurs proposées peuvent être modifiées par l'utilisateur. Possibilité d'indiquer l'altitude

2- Possibilité d'indiquer longueur, profondeur, température, présence de siphon, année de découverte (voir si on propose de déclarer la cavité sensible)

**Comment by Clm-Roig** [comment]
Pull request (merged) about the API endpoint here: https://github.com/GrottoCenter/Grottocenter3/pull/649

(not in production currently)

**Comment by Clm-Roig** [comment]
For the cave choice, it's now possible to use the `resourceType` value `"caves"` to search on Grottocenter caves as explained here: https://github.com/GrottoCenter/Grottocenter3/pull/650
