### ISSUE TITLE
[ENTRANCE PAGE] Creation / Editing Entrance history

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#404]
Depuis la page d'une cavité mettre en place la possibilité de créer un historique à partir d'un bouton.
Et pour les historiques existants mettre en place un bouton permettant d'éditer cet historique.

Ces fonctionnalités sont accessibles pour toutes les personnes connectées

Un historique est constituée d'un titre, d'un texte et de la langue utilisée pour cette description. Il faudra faire figurer un texte indiquant qu'en validant la personne accepte que sa contribution soit placée sous la licence CC BY SA

**Comment by bsoufflet** [comment]
Pas de titre en BDD.

**Comment by bsoufflet** [comment]
Je reprend ce ticket @Taha949 @hafidinferno @urien @Clm-Roig
