### ISSUE TITLE
[ENTRANCE PAGE] Creation / Editing Entrance rigging

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#405]
Depuis la page d'une cavité mettre en place la possibilité de créer un tableau décrivant l'équipement nécessaire, à partir d'un bouton.
Et pour les tableaux d'équipement existants mettre en place un bouton permettant de les éditer.

Ces fonctionnalités sont accessibles pour toutes les personnes connectées

La fiche d'équipement prend place dans un tableau d'un titre et d'une langue. Le tableau sera proposé avec une ligne vide lors de la création mais l'utilisateur aura la possibilité de rajouter ou retirer des lignes.

. Il faudra faire figurer un texte indiquant qu'en validant la personne accepte que sa contribution soit placée sous la licence CC BY SA

**Comment by Souterweb** [comment]
Pour les fiches d'équipement actuellement visibles sur Grottocenter V3 
j'ai remarqué des soucis de mise en page.
Certaines tabulations ou mises en forme des tableaux des fiches 
d'équipement de l'ancienne V2 ont été mal "interprétés" par des "\n".
Hélas comme je n'ai pas les anciennes fiches V2 je ne sais pas à quoi ça 
correspond.

Pour mieux comprendre voir ci-dessous :




Domi



Le 14/04/2022 à 07:45, Urien a écrit :

**Comment by urien** [comment]
Example https://grottocenter.org/ui/entrances/45
