### ISSUE TITLE
[ENTRANCE PAGE] Creation / Editing  Entrance description

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#41]
Depuis la page d'une cavité mettre en place la possibilité de créer une description à partir d'un bouton.
Et pour les descriptions existantes mettre en place un bouton permettant d'éditer la description.

Ces fonctionnalités sont accessibles pour toutes les personnes connectées

Une description est constituée d'un titre, d'un texte et de la langue utilisée pour cette description. Il faudra faire figurer un texte indiquant qu'en validant la personne accepte que sa contribution soit placée sous la licence CC BY SA

**Comment by bsoufflet** [comment]
Je reprends cette tache également. J'ai presque terminé :)
