### ISSUE TITLE
[MAP] - Performance improvement

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/grottocenter-front#417]
When zooming at the entrance marker level on area with a lot of entrances (200+ markers) we could improve the performance by : 
- making the markers lighter (simple circle instead of image icon marker) ?
- not attaching an already rendered popup and a tooltip to each marker and instead create the popup when we click the marker
- OR do not attach the popup to each marker if there is too much markers and instead add in the tooltip that the user need to oom more to activate the popups
- upgrade to the latest react-leaflet 4.0.0 + leaflet 1.8 versions
- upgrade MUI to v5 (planed here #289) -> https://github.com/mui/material-ui/issues/21657#issuecomment-707140999

@see #360

**Comment by urien** [comment]
Réalisé
