### ISSUE TITLE
[Home Page] Add user guide ling in footer

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#418]
**Is your feature request related to a problem? Please describe.**
Nous venons de créer les pages "mode d'emploi", il faut créer un lien pour y donner accès

**Comment by Souterweb** [comment]
Le 26/04/2022 à 07:32, Urien a écrit :
> Nous venons de créer les pages "mode d'emploi"

Nous "sommes en train de créer" pour être plus précis...   ;o)

Domi
