### ISSUE TITLE
[NETWORK - CAVE] Edit

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#435]
Un bouton sur la page des réseaux, identique a celui existant sur la page des entrées permet d'ouvrir une fenêtre permettant de changer :

- le nom de la cave (name)
- la profondeur (depth)
- le développement (length)
- la valeur du champ isDiving

Valider la modification fait recharger les données de la cavité / réseau depuis le serveur et le ré-affiche (comme pour l'entrée).

**Comment by Clm-Roig** [comment]
Fixed by #460
