### ISSUE TITLE
[Entrance Edit] Change cave

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#436]
### Needs https://github.com/GrottoCenter/Grottocenter3/issues/852 to be done before

**Is your feature request related to a problem? Please describe.**
Lors qu'on édite une cavité il doit être possible de raccorcher l'entrée à un réseau ou de la changer de réseau

**Describe the solution you'd like**
Depuis la fenêtre d'édition, à coté de la mention présente sur l'image ci-dessous ajouter un bouton
![image](https://user-images.githubusercontent.com/1165144/167175394-4b6ab1b9-f558-4738-a2b1-d06443fbea40.png)

Ce bouton, selon le cas portera la mention "Lier la cavité ou un réseau existant" ou "Lier la cavité a un nouveau réseau"
Le clic sur ce bouton remplace la femetre par une fenetre permettant de sélectionner une autre cave et de valider.
La validation permet d'afficher la page de la cavité mise à jour

**Comment by Clm-Roig** [comment]
Je précise, comme discuté il y a quelques semaines, qu'il me paraît judicieux de faire ce développement dans un composant dédié à ce changement de réseau (ce qui ne contredit pas le premier message de cette issue). Plusieurs raisons à cela : 
- C'est une opération lourde de conséquences. Il faut explique très précisément ce que ça implique avec un long texte et demander confirmation à l'utilisateur avant de l'exécuter.
- La tâche est complexe pour le serveur. Il risque d'y avoir des erreurs, il faudra les afficher proprement et être verbeux quant au problème survenu. 

Le composant pourrait alors être appelé depuis le formulaire d'édition (comme expliqué ci-dessus) soit depuis la page de l'entrée directement éventuellement.

**Comment by Clm-Roig** [comment]
L'API n'est pas prête pour cette feature. J'ai quelques questions à ce propos là-bas : https://github.com/GrottoCenter/Grottocenter3/issues/852

**Comment by bsoufflet** [comment]
Dans le cas du déplacement de la dernière entrée d'un réseau A vers un autre réseau B on se retrouve donc avec une suppression du réseau A (comme précisé dans l'issue de back). Il serait bon coté front de détecter ce cas et de mettre un message clair.
en effet, rien ne sera réellement perdu grace à notre is_deleted mais il faudra :
- lié le réseau A au réseau B (en cas d'accès à l'ancienne URL pour éviter une 404). C'est déjà dans le modèle il me semble.
- indiquer que les données speleométrique du réseau A seront "supprimées"
- indiquer qu'il existe des informations encyclopédiques sur A et qu'il faut choisir de les "supprimer" ou de les transférer sur B (ou bien plus simple qu'elles seront forcément supprimées et qu'il faut les gérer manuellement avant) ?
