### ISSUE TITLE
Add a loading screen while the react app is preparing and JS is loading

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/grottocenter-front#445]
The Grottocenter front app is slow to load due to large javascript file to load the first time (then in cache) and due to the react DOM rendering.

We should maybe display a loading screen instead of a white page which may feel like a bug.

Maybe this solution could work while waiting for the React app to render all components : https://betterprogramming.pub/a-quick-and-easy-react-js-loading-screen-with-hooks-940feccd553f
But the above solution may not work during the downloading of the large javascript files (8+ Mo)...

**Comment by Clm-Roig** [comment]
Why not rendering a spinner directly in the index.html file ? And remove it when the window is ready using vanilla JS : 

```js 
window.onload = function(){
    // remove spinner
};
```

**Comment by Souterweb** [comment]
Testé le logo d'attente : c'est excellent ! 
On en arrive presque a regretter l'époque où c'était bien plus lent pour avoir le temps de l'admirer...  ;o)
Bravo.
Domi

**Comment by urien** [comment]
Traité par Vincent : super fonctionnalité !
