### ISSUE TITLE
[ADV SEARCH] Search by publication date

### ISSUE THREAD

**Issue by AxelCanton** [GrottoCenter/grottocenter-front#46]
At the moment, any results returned by the API don't contain the publication date of the document.
![Sans titre](https://user-images.githubusercontent.com/58460876/121920651-8a794c80-cd38-11eb-893d-71016326d5a1.png)

This is probably the reason why it is impossible to search for a document with the date field.

**Comment by Clm-Roig** [comment]
Je m'en occupe, j'ai trouvé comment corriger le souci :slightly_smiling_face:
