### ISSUE TITLE
[LEADER DASHBOARD] Notification list

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#463]
Les fédérations, les gestionnaires de sites, les responsables de Wikicaves doivent pouvoir recevoir des notifications quand de nouveaux contenus sont ajoutés ou des modifications interviennent sur des cavités situées dans les pays ou dans les massifs de leur choix.

Une nouvelle carte, accessible aux personnes ayant le status de leader, leur permet de faire une recherche et de sélectionner plusieurs pays et/ou plusieurs massifs.

Éventuellement on peut envisager de permettre a ces personnes de sélectionner la fréquence des notifications.

**Comment by Clm-Roig** [comment]
Je ferme au profit de #480 et #481 qui divise le problème en deux (gestion des abonnements et affichage des notifications).
