### ISSUE TITLE
[CARD VIEW] Redimensionnement de la carte en plein écran (Resize the map to full screen)

### ISSUE THREAD

**Issue by Domi-le-webmaster** [GrottoCenter/grottocenter-front#465]
_English below_

**Problème** : En mode carte, lorsqu'on replie la frame du menu de gauche pour disposer d'une meilleure lisibilité, une partie de l'écran du côté droit reste blanche, la carte n'occupe donc pas la totalité de l'espace écran disponible.

**Remarque** : Cette partie blanche inoccupée à droite fait exactement la surface de la frame de menu de droite qu'on vient de fermer.

**Situation** : Ce problème est très gênant pour une utilisation sur smartphone à cause de la toute petite taille de l'écran. De fait, la carte en devient inutilisable car elle n'occupe plus qu'un tiers de la largeur de l'affichage. Bref : on n'y voit rien.

**Objectif** : Il faudrait que quand on cache la frame de gauche avec l'icône /// la carte se redimensionne automatiquement pour occuper toute la largeur disponible à l'écran.

----------------------------------------------------------------------

**Problem** : In map mode, when you fold the left menu frame for better readability, a part of the screen on the right side remains white, so the map does not occupy all the available screen space.

**Note**: This unoccupied white part on the right is exactly the same area as the right menu frame that we just closed.

**Situation** : This problem is very annoying for a use on smartphone because of the very small size of the screen. In fact, the map becomes unusable because it occupies only one third of the display width. In short: you can't see anything.

**Purpose**: When you hide the left frame with the /// icon, the map should be automatically resized to occupy all the available width on the screen

**Comment by Clm-Roig** [comment]
Doublon de #389, je ferme ici 🙂
