### ISSUE TITLE
[Entrance view] Bug on document presentation

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#475]
Les documents associés à une cavité étaient présentés de manière complète avec le nom du document, le type de document un lien vers le fichier s'il existe et la licence qui s'applique.
Désormais ce n'est plus le cas
![image](https://user-images.githubusercontent.com/1165144/169964204-1517303e-2095-4f9b-a5d3-a480c33bcb91.png)

**Comment by Clm-Roig** [comment]
J'ai corrigé ce bug côté API il y a quelques jours. Au prochain déploiement de celle-ci ce sera réglé 😉
