### ISSUE TITLE
[ENTRANCE] Add "average rating" above general rating

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/grottocenter-front#478]
il faudrait indiquer une mention "Cotations moyennes" (dans la même petite police que "Localisation" ou "Coordonnées") au dessus du triplet des cotations de gauche.

In english : "average rating"

![image](https://user-images.githubusercontent.com/985903/170582865-ade10611-2241-4fb1-b922-1c82ead9c71a.png)

**Comment by urien** [comment]
done
