### ISSUE TITLE
Refactor-caves&massifs-PostGis 

### ISSUE THREAD

**Issue by lageta** [GrottoCenter/grottocenter-front#479]
Ce bout de code risque de casser pas mal de choses côté client où l'on accède au massif avec `entrance.massif` en espérant en avoir qu'un seul... On ne pourra pas merger cette PR tant que le client n'aura pas intégré ce changement.

_Originally posted by @Clm-Roig in https://github.com/GrottoCenter/Grottocenter3/pull/831#discussion_r862384181_

**Comment by Clm-Roig** [comment]
Pas besoin de créer une issue : une fois que j'ai validé ta PR, j'irai faire la modif sur le front avant de merger la-dite PR côté API 😉

**Comment by lageta** [comment]
> Pas besoin de créer une issue : une fois que j'ai validé ta PR, j'irai faire la modif sur le front avant de merger la-dite PR côté API 😉

Super ça va me faire économiser du temps ! Merci beaucoup ^^
