### ISSUE TITLE
[Entrance] problem to visualize some data

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#482]
Un utilisateur souhaite visualiser la  page d'une entrée
https://grottocenter.org/ui/entrances/13

Quand il n'est pas connecté la page ne s'affiche pas
![image](https://user-images.githubusercontent.com/1165144/170991031-b219d594-e7b3-4e08-989d-68da3b9c87c4.png)

Quand il est connecté certaines données ne s'affichent pas
![image](https://user-images.githubusercontent.com/1165144/170991220-61876662-a29d-4e2e-8216-193da63f3cd5.png)

Il utilise un ordinateur sous Windows 10.

De mon côté les coordonnées s'affichent ainsi que deux localisations

**Comment by Clm-Roig** [comment]
Cette cavité est sensible, il ne peut donc pas la visualiser sans être connecté. 

Je n'arrive pas à reproduire le souci d'affichage par contre. A-t-il essayé d'actualiser la page ? Est-ce que le bug est toujours présent ? Sur quel navigateur est-il ? (c'est plus déterminant que l'OS 😉)

**Comment by urien** [comment]
Le pb a été observé avec Edge. Je viens de tester et pour moi cela fonctionne normalement

**Comment by Clm-Roig** [comment]
Pareil, pas de problème sous Edge... Je ferme pour le moment, si jamais tu as plus d'infos, n'hésite pas à réouvrir.
