### ISSUE TITLE
[API DOCUMENTATION] Make swagger available 

### ISSUE THREAD

**Issue by maximenathan** [GrottoCenter/grottocenter-front#5]
Since the migration to the new `grottocenter-front`, Swagger (Route `ui/swagger/1`) is no longer working.

![image](https://user-images.githubusercontent.com/7127156/129358037-6d52aa2e-50bb-4cef-adaf-dfa1901ff6f2.png)

## TODO 

- Get the API documentation using the following route & Redux;
`Route : GET api/v1/swagger.yaml`
See GrottoCenter/Grottocenter3#652 for more details.

- Change the documentation URL from `ui/swagger/1` to `ui/api-doc/v1`

**Comment by Clm-Roig** [comment]
Maybe the API documentation should be serve by the API directly, inside a plain and single html page ? Or the API only serves the _apiV1.yaml_ file ?

**Comment by urien** [comment]
Pourquoi pas. 
Est ce que cela a du sens de faire une page sur le wiki et de la maintenir ? C'est quelque chose que je peux faire mais cela n'a rien d'automatique

**Comment by Clm-Roig** [comment]
Il faut que le fichier de l'API reste un fichier yaml lu par Swagger, versionné par Git et modifié par les développeurs quand ils développement une nouvelle route. Si on le découple du développement en le mettant dans un wiki, on oubliera d'aller mettre à jour la doc après avoir créé une nouvelle route.

**Comment by Clm-Roig** [comment]
[Ici](https://github.com/GrottoCenter/Grottocenter3/pull/544#issue-860229712), @bsoufflet disait : 

> Now this application is only an API. The only file statically served is the swagger file.

Mais je n'arrive pas à obtenir la doc, quelque soit la route utilisée...

**Comment by maximenathan** [comment]
https://www.npmjs.com/package/swagger-ui-react

C'est possible de retourner un json swagger via un call api ?

**Comment by bsoufflet** [comment]
En effet j'avais écris cela mais en fait je n'ai pas ajouter le mécanisme pour "Servir" le fichier Swagger...
Je pense que l'idéal serait en effet de juste servir le fichier yaml via l'API ou bien en tant que fichier static.
l'extension swagger-ui-react saura ensuite parsé le fichier YAML d'après la doc.

Cependant j'ai supprimé toutes les taches grunt qui permettait de déplacer les fichiers de assets vers le bon dossier .tmp/public ...
Il faudrait donc soit remettre en place le système de d'assets static avec le middleware serve-static (vori https://sailsjs.com/documentation/concepts/assets) ou bien ajouter une nouvelle route au router pour servir ce fichier si c'est possible...

**Comment by Clm-Roig** [comment]
On peut servir le fichier yaml en API REST avec `res.sendFile()` grâce à Express => https://expressjs.com/fr/api.html#res.sendFile 
Je peux faire une route GET /doc en 5min sur le back si besoin.

**Comment by bsoufflet** [comment]
> On peut servir le fichier yaml en API REST avec `res.sendFile()` grâce à Express => https://expressjs.com/fr/api.html#res.sendFile Je peux faire une route GET /doc en 5min sur le back si besoin.

Oui ce serait très bien !
Une route GET /swagger-doc :) (mieux que juste /doc qui est peut etre trop générique?)

**Comment by bsoufflet** [comment]
Je me demande si il ne faudrait meme pas que la route soit `GET /doc/swagger-v1.yaml` ?
Comme cela, si un jour on a une v2 on aura une 2ème route à créer en plus de celle là qui sera `GET /doc/swagger-v2.yaml`

**Comment by Clm-Roig** [comment]
Le prefix de la route étant api/v1, on aura donc GET api/v1/swagger-v1.yaml : on aura bien la différenciation entre la doc v1 et la doc v2

**Comment by bsoufflet** [comment]
si le prefix est `api/v1` on pourrait juste avoir la route `GET api/v1/swagger.yaml` non ?

**Comment by Clm-Roig** [comment]
Ah oui bien sûr, je me suis emmêlé. 

GET api/v1/swagger.yaml ce serait parfait

**Comment by Clm-Roig** [comment]
La PR côté back qui détaille la route à utiliser :
https://github.com/GrottoCenter/Grottocenter3/pull/652

Route : GET api/v1/swagger.yaml
