### ISSUE TITLE
[ADV SEARCH] Improve CSV export file name

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/grottocenter-front#51]
Lors de l'export CSV, le fichier créé (chez moi), est un fichier texte nommé "unknown" sans extension.

- il faudrait qu'au moins le fichier soit créé avec l'extension csv pour etre ouvrable par le grand-public
- eventuellement que le fichier soit nommé. par exemple "bbs-keyword1-keyword2.csv"

**Comment by urien** [comment]
Je viens de faire un test (sur l'appli front, avec Firefox sous windows) et j'obtiens bien un fichier avec l'extension csv (R++2O7Fo.csv)
Le nom semble provenir d'une production aléatoire. L'utilisateur peut choisir de lui en donner un autre s'il préfère.
Il me semble assez lourd d'indiquer dans le nom du fichier les critères de recherche qui ont été fixés par l'utilisateur. cela ne me semble pas être un développement prioritaire

**Comment by urien** [comment]
Le fichier créé a bien une extension csv
