### ISSUE TITLE
[DOCUMENT] problem to save a file

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#54]
Je viens d'essayer de créer un document et lorsqu'on soumet un document l'enregistrement ne se termine pas
Voila l'erreur retournée (CORS) :

```
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.grottocenter.org/api/v1/documents. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

**Comment by urien** [comment]
Bon, si j'essaye de créer un document sans fichier attaché, comme utilisateur, j'ai un message me disant que je n'en ai pas l'autorisation

**Comment by urien** [comment]
Rebon, si je suis administrateur je n'ai pas non plus le droit de soumettre un document

**Comment by urien** [comment]
Désormais il est possible de créer et valider un document sans fichier. Par contre l'ajout d'un fichier plante (la requete tourne indéfiniement)
Dans la console on a l'erreur suivante (CORS) :

```
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.grottocenter.org/api/v1/documents/130192. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

**Comment by urien** [comment]
Je viens de refaire un test : cela fonctionne lorsqu'on créé un document avec un fichier. Peut être que le pb n'existe que lorsqu'on met à jour un document en lui rajoutant un fichier

**Comment by Clm-Roig** [comment]
Concernant les droits, sur la prod j'ai ça : 

![image](https://user-images.githubusercontent.com/20704943/141678723-d76d2cf7-079c-4fe1-8d02-0846b89431f1.png)


Est-ce que déjà c'est bon ? Si ces droits sont bons, je regarderai le code de l'API et pousserai un correctif. 

Restera donc, dans cette issue, à gérer cette histoire de fichier / pas fichier lors de la création ou de la modification.

**Comment by urien** [comment]
Oui les droits sont bons sauf delete.
Le delete n'est autorisé qu'aux admistrateurs pour tous les objets.
Mais c'est sans relation avec le sujet de cette issue

**Comment by urien** [comment]
Aujourd'hui je ne peux pas créer un document avec un fichier avec la même erreur

**Comment by Clm-Roig** [comment]
Corrigé, je ferme !
