### ISSUE TITLE
[DOC EDIT] Editor is not deduced from parent

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#58]
Pour les numéro l'éditeur est défini par le document parent, il n'est donc pas possible de le saisir. Mais il n'est pas possible de cliquer sur le bouton suivant tant qu'on n'a pas saisi un éditeur.
Du coup il n'est pas possible de modifier les numéros

![image](https://user-images.githubusercontent.com/1165144/141152268-a33e9353-edab-4ed6-afc8-e73d235d690d.png)

**Comment by urien** [comment]
Ce problème n'existe pas pour les articles : l'editeur du document parent est directement renseigné

**Comment by Clm-Roig** [comment]
Je ne suis pas sûr d'avoir compris et je n'arrive pas à reproduire ton problème... 
Le souci se produit dans quel cas ? Une description du problème avec 1) état initial 2) modifs effectuées et 3) état final (buggué donc) m'aiderait beaucoup.

**Comment by Clm-Roig** [comment]
Chez moi, dès qu'on rentre une collection (obligatoire pour une Issue donc), l'éditeur est déduit obligatoirement. 

Est-ce que le problème n'est pas plutôt qu'il existe des collections sans éditeur das la base de données ?

**Comment by urien** [comment]
Je te propose d'ouvrir une issue (un numéro).
Par exemple https://beta.grottocenter.org/ui/documents/25621
Si tu essaye de l'éditer, à l'étape 2 (classification) l'éditeur n'est pas
renseigné mais on ne peut pas le saisir. Pourtant l'éditeur de la
collection est bien renseigné
https://beta.grottocenter.org/ui/documents/21383
Comme il n'y a pas d'éditeur il n'est pas possible d'aller à l'étape 3

Il faudrait que l'éditeur de la collection soit indiqué automatiquement et
qu'on ne puisse pas le modifier



Le sam. 13 nov. 2021 à 16:56, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
D'accord, je crois que j'ai compris d'où venait le bug grâce à cet exemple, merci !

### :warning: EDIT : ce n'est pas ça, cf commentaire suivant :arrow_down: 

~Dans ce formulaire, habituellement utilisé pour la soumission et l'édition de document AVANT validation par les modérateurs, on utilise l'attribut `partOf` pour déduire les données provenant du document parent.~

~Ici, il faudrait chercher dans l'attribut `parent`.~

**Comment by Clm-Roig** [comment]
### :warning: EDIT : ce n'est pas ça encore, cf commentaire suivant :arrow_down: 

Hum le problème est plus complexe que ça. 

~Lorsque le document est soumis, son éditeur n'a pas été enregistré vu qu'on le déduit de son parent. De ce fait, on est sûr d'avoir toujours le même éditeur que celui du parent même s'il change.~

~Pour cette issue, il faut modifier le composant pour chercher d'abord dans `editor`, sinon dans `partOf.editor`.~

**Comment by Clm-Roig** [comment]
Bon en fait je crois juste que ce n'est pas possible actuellement et qu'on est face à des issues "malformées".
Lorsque l'on soumet une issue, on soumet forcément un éditeur avec. Pour moi, la meilleure façon de fixer ce bug c'est de : 
- mettre à jour la BD pour mettre un éditeur à toutes les collections (1000 sur 1500 sont sans éditeur)
- mettre à jour la BD pour mettre un éditeur à toutes les issues (en passant par leur collection parent)
- vérifier qu'on a bien une vérification côté serveur qui s'occupe de vérifier qu'on a bien un éditeur lorsque l'on soumet une issue

**Comment by Clm-Roig** [comment]
En production : 

- 48 000 issues n'ont pas d'éditeur
- Elles ont toute une collection ...
- ... mais on a 1000 (parmi 1500) collections sans éditeur.

Autant dire que ça va être compliqué d'avoir des données homogènes avec ça

**Comment by urien** [comment]
Ok je comprends

**Comment by urien** [comment]
Je vais créer un éditeur par collection. Mais pour certaine collections il n'est pas possible d'imaginer quel peut être l'éditeur.
Et on a vraiment beaucoup de doublons
Est ce que cela convient si je propose une liste de document à supprimer directement en base de données de manière a avoir une liste cohérente de collections et d'issues ?
A partir de cette liste on pourrait trouver une solution concernant les éditeurs des issues

**Comment by Clm-Roig** [comment]
Pas de soucis pour une liste de docs oui (par leur id évidemment)

**Comment by urien** [comment]
Actuellement je ne peux pas éditer les collections
https://github.com/GrottoCenter/grottocenter-front/issues/59
cela fonctionnait il y a quelques jours mais plus maintenant
je m'y colle dès que c'est possible

Le dim. 14 nov. 2021 à 11:26, Clément Roig ***@***.***> a
écrit :

**Comment by urien** [comment]
Pour régler le problème plus rapidement je propose que l'éditeur soit toujours déduis du document parent mais qu'on laisse la possibilité de le modifier. Cela permettrait a tous de travailler immédiatement. Sinon on va avoir quelque chose qui ressemble à un bug durant de longs mois
