### ISSUE TITLE
[DOCUMENT] Cannot save an edited document

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#59]
Je souhaite modifier le document ci-dessous et lorsque je clique sur sauvegarder le processus n'aboutit pas

https://beta.grottocenter.org/ui/documents/edit/22081
Mais avec  https://beta.grottocenter.org/ui/documents/edit/22082

j'ai le même problème qui est peut être un problème général

**Comment by urien** [comment]
A priori il n'y a pas de problème pour enregistrer un article édité

**Comment by urien** [comment]
Cela semble concerner seulement les collections.
Dans la console il apparait que c'est bloqué par un outil de développement
![image](https://user-images.githubusercontent.com/1165144/142219400-87164d5a-81d9-4834-a032-1ffdc51e1149.png)

**Comment by Clm-Roig** [comment]
On peut fermer non ? Il me semble que désormais c'est ok !

**Comment by urien** [comment]
Oui

Le jeu. 25 nov. 2021 à 16:45, Clément Roig ***@***.***> a
écrit :
