### ISSUE TITLE
[DOCUMENT] spellchecking

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#62]
Il ne faut pas de e à entité**e**s liées
Dans le fichier transifex c'est bon
![screenshot-beta grottocenter org-2021 11 15-17_55_59](https://user-images.githubusercontent.com/1165144/141822559-89eb6892-4b98-41a0-b6c1-4d5bda7df6d1.png)

**Comment by Clm-Roig** [comment]
C'est corrigé, merci !
