### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#622]
Voici les chaînes de caractères qui, en date du 27/07/2022 ne sont pas encore traduites en français mais qui n'apparaissent pas encore comme "à traduire" dans Transifex : 

- [x] sur la page de création d'une nouvelle entité (https://grottocenter.org/ui/entity/add) > "Organization"
- [x] sur la page 1 de création d'une nouvelle cavité (https://grottocenter.org/ui/entity/add) > "Custom message"
- [x] sur la page 2 de création d'une nouvelle entrée (https://grottocenter.org/ui/entity/add) > "The cave access is restricted"
- [x] sur la page 1 de création d'un nouveau massif (https://grottocenter.org/ui/entity/add) > "Description of the massif"
- [x] sur la page 1 de création d'une nouvelle organisation (https://grottocenter.org/ui/entity/add) > "Custom message"
- [x] idem mais sur la page 2 (informations) > First adress / Zip code"
- [x] en cas d'erreur de saisie du mail lors de la connexion d'un utilisateur au site "You must provide a valid email" 
- [x] sur la page cavité dans la section association de document, étape 2 : dans le bandeau marron "Unselect document" / bouton "ASSOCIATE"
- [x] sur la page de création d'un nouveau document BBS toutes les bulles explicatives sont en anglais par exemple "An article from a source".
- [x] toujours sur la page de création d'un document BBS, à la fin au moment de la relecture avant de soumettre on a "TYPE DE DOCUMENT : Issue" ce qui en français n'a aucune signification (et je crains qu'en anglais non plus d'ailleurs).

À suivre...

**Comment by urien** [comment]
Peux tu transférer vers une issue sur le front ?

**Comment by Souterweb** [comment]
Le 20/06/2022 à 10:28, Urien a écrit :
> Peux tu transférer vers une issue sur le front ?

Heuuu...

Transférer quoi vers où ?

J'ai bien peur de ne pas encore savoir faire ça.

Github et moi on en est au tout début de notre relation...    ;o)

Domi

**Comment by Souterweb** [comment]
Je complète la liste directement en haut de cette page au fur et à mesure que je trouve des textes non traduits.

**Comment by Clm-Roig** [comment]
Merci @Souterweb pour cette issue ! Je viens de soumettre une Pull Request pour corriger tout ça 🙂 Ce sera bientôt en ligne !
