### ISSUE TITLE
[CSV IMPORT] Taking into account of the parent document indicated in dct: isPartOf

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#64]
Pour le fichier joint j'ai l'erreur
AdapterError: Unexpected error from database adapter: insert or update on table "t_document" violates foreign key constraint "t_document_t_identifier_type_fk"
J'ai déclaré comme creator " " car c'est une valeur obligatoire et que je n'ai pas de valeur à mettre
[issues ecokarsttest.csv](https://github.com/GrottoCenter/grottocenter-front/files/7540636/issues.ecokarsttest.csv)

**Comment by urien** [comment]
Je viens de refaire un test avec le fichier joint. cela me conduit à renommer l'issue
Il ne faut pas indiquer URL dans la colonne dans dct:identifier. Par contre l'url dans dct:source est bien récupérée.
Il faut un nom pour le créateur
Dans la colonne dct:isPartOf il faut indiquer le document parent (ici la collection dans laquelle se trouve le numéro) J'ai mis l'id de la collection mais cette valeur n'est pas traité
Au niveau traitement, si la colonne dct:isPartOf a une valeur il ne faudrait pas prendre en compte la colonne dct:publisher
[issues ecokarsttest.csv](https://github.com/GrottoCenter/grottocenter-front/files/7545335/issues.ecokarsttest.csv)
[issues ecokarsttest.csv](https://github.com/GrottoCenter/grottocenter-front/files/7545354/issues.ecokarsttest.csv)

**Comment by urien** [comment]
Cela ne fonctionne pas non plus si on remplace l'id par l'URL

**Comment by Clm-Roig** [comment]
Ce bug est corrigé non @urien ?

**Comment by urien** [comment]
Je n'ai pas testé encore

Le jeu. 25 nov. 2021 à 16:44, Clément Roig ***@***.***> a
écrit :

**Comment by urien** [comment]
Testé, cela fonctionne très bien : merci !
