### ISSUE TITLE
[Document show] Page is not loading

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#663]
**Describe the bug**
Quand on demande à voir un document la page reste blanche.
C'est très ennuyeux...  lundi j'ai présentation du BBS au congrès

**Comment by Clm-Roig** [comment]
C'est certainement ma faute, je regarde très rapidement.

**Comment by urien** [comment]
Pour moi cela ne fonctionne toujours pas
https://grottocenter.org/ui/documents/16106

**Comment by Clm-Roig** [comment]
Ce n'est pas encore déployé, je revérifie dans quelques minutes quand c'est le cas et je ferme si c'est ok

**Comment by urien** [comment]
Merci

**Comment by Clm-Roig** [comment]
C'est bon !

**Comment by urien** [comment]
Ouf !
