### ISSUE TITLE
[DOCUMENT edit create] Impossible to create a new organization

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#689]
**Describe the bug**
Depuis le formulaire de création et d'édition d'un document il est normalement possible de créer une organisation si elle n'existe pas déjà.
Cela ne fonctionne plus.

Cela vient sans doute des modifications réalisées sur les apis suite à la mise en place des fonctionnalités permettant de créer et d'éditer les organisations comme entités indépendantes.

Il est possible que la fonctionnalité permettant de créer un auteur depuis un document rencontre le même type de pb. Dans l'immédiat je ne souhaite pas créer un faux auteur pour réaliser le test

**Comment by Clm-Roig** [comment]
Après avoir testé sur la prod, j'ai bien pu créer une organisation mais son nom est vide. 

C'est un souci côté front, on n'envoie pas les données au bon format. Je transfère sur l'autre repo.

**Comment by Clm-Roig** [comment]
Fixé par [42ab37d](https://github.com/GrottoCenter/grottocenter-front/commit/42ab37d69a78fdc4f5dae287193fc65abf86c413), je ferme. 

Je n'ai pas testé pour les auteurs mais vu le code, ça doit marcher. Il y avait un souci avec les organisations parce qu'elles utilisent un name "traduisible" qu'on stocke à part dans une table de la BD. Le nom d'un auteur ne demande pas ça, on le passe directement comme une string "tel quel".
