### ISSUE TITLE
[Entrance Create] impossible to create an entrance

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#690]
**Describe the bug**
Comme utilisateur, lorsqu'on souhaite créer une entrée, la requete n'aboutit pas et on a un message "bad request"

![image](https://user-images.githubusercontent.com/1165144/183247113-e0bada5a-b849-46b0-80d8-1412ad49e88e.png)

Cela a été raporté par dlap et j'ai eu le même résultat avec l'utilisateur fredericurien@gmail.com

**Comment by Clm-Roig** [comment]
Ce n'est pas indiqué dans l'interface mais la profondeur et la longueur doivent être des entiers.
