### ISSUE TITLE
[CAVE Show] impossible to show the cave page if entrance is "sensible"

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#712]
**Describe the bug**
pour une entrée sensible, par exemple https://grottocenter.org/ui/entrances/6074
Si on clique sur le lien de la cavité https://grottocenter.org/ui/caves/6074
On arrive sur une page blanche

**Comment by Clm-Roig** [comment]
Erreur de React : 
![image](https://user-images.githubusercontent.com/20704943/184080180-b3621ce5-7e7b-4404-b8aa-ce37adc13dbb.png)

J'imagine que l'entrance sensible étant vidée de ses coordonnées, on ne peut pas obtenir la longitude et la latitude.

Il faut donc corriger ce problème et revoir l'affichage de la carte de la cave pour y mettre un message qui dit quelque chose du genre "certaines entrées de cette cavité ne sont pas affichées car elles sont à accès restreint", qu'en penses-tu ?

**Comment by urien** [comment]
Effectivement il faudrait faire sur la page des caves concernées quelque chose qui s'inspire de ce qui existe pour les entry
