### ISSUE TITLE
[Entrance Cave show] The entrance(s) is(are) no longer displayed on the map

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#720]
**Describe the bug**
The entrance is no longer displayed on the map
![image](https://user-images.githubusercontent.com/1165144/185307050-4ccf758e-d788-4a12-b705-08abc5ec90f0.png)
this is also the case for the caves
![image](https://user-images.githubusercontent.com/1165144/185307197-cabf52f3-a5cb-4cb9-9d85-b66672fb005e.png)

**Comment by Clm-Roig** [comment]
Peut-être lié à #719

**Comment by urien** [comment]
Effectivement je l'ai repéré après
