### ISSUE TITLE
[LOCATION DESCRIPTION HISTORIQUE COMMENTAIRE RIGGINGS] Delete

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#724]
**Is your feature request related to a problem? Please describe.**
Quand une localisation, une description, un historique, un commentaire, une fiche d'équipement a été créée à des fins de test, de spam ou suite à une erreur, il n'est pas possible de la supprimer

**Describe the solution you'd like**
Ajout d'un bouton "supprimer" visible uniquement par les administrateurs et les modérateurs.
Ajout d'un bouton "alerter" visible par les autres utilisateurs
Le clic sur le bouton "supprimer" ouvre une fenêtre de validation. La validation entrainant la suppression du bloc de localisation (le passage de isDeleted à true) et l'affichage de la page de la cavité mise à jour
Le clic sur le bouton "alerter" ouvre la page https://en.wikicaves.org/contact

**Comment by Clm-Roig** [comment]
> Il faudra ajouter le code nécessaire pour que les blocs de localisation ne s'affichent que si le champ isdeleted est à false

Je pense que c'est une feature "à part" de cette issue et qui va demander un peu de réflexion : 
- Pour les utilisateurs => l'API peut ne pas leur renvoyer les "isDeleted" directement, donc rien à changer côté front
- Pour les admins => est-ce qu'ils doivent pouvoir voir ces contributions ? Autant les leur cacher non ? Ou sinon il faut qu'elles soient affichées différemment. 

Tu peux copier / coller ou répondre sur une nouvelle issue éventuellement @urien ? Histoire que celle-ci reste focalisée sur la suppression uniquement 🙂

**Comment by urien** [comment]
Du coup, il n'y a rien à faire si les localisations supprimées ne sont pas visibles par les utilisateurs

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-front/pull/980
