### ISSUE TITLE
[ADMIN DASHBOARD] user dashboard do'nt word

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#737]
**Describe the bug**
Comme administrateur l'affichage de la liste des administrateurs, leaders, modérateurs n'aboutit pas

**To Reproduce**

Se connecter comme administrateur
Cliquer sur dashboard / manage user

**Screenshots**
![image](https://user-images.githubusercontent.com/1165144/189471088-65fad597-8fca-4929-ad66-732deccd4787.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser [Firefox]
- Version [latest]

**Additional context**

**Comment by Clm-Roig** [comment]
Ça marche chez moi. Tu as peut-être essayé à un moment où un déploiement était en cours ?

**Comment by urien** [comment]
Ok, c'était sans doute cela
