### ISSUE TITLE
[Massif edit] problem with the polygon

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#750]
**Describe the bug**
Quand je souhaite éditer un massif qui a déjà un polygone de défini
https://grottocenter.org/ui/massifs/586/edit
Le polygone déjà en place n'est pas conservé. Quand je le retrace il disparait à l'étape vérification des données

**Comment by Souterweb** [comment]
Et moi je n'arrive pas à définir un polygone pour limiter un massif qui n'en a pas encore. Je le trace mais il ne s'enregistre pas au moment de passer à l'étape suivante (vérification des données). Je pense que c'est une variante du même souci.

**Comment by urien** [comment]
Work on Api resolve this problem

**Comment by urien** [comment]
En fait le problème est réglé pour la création d'un massif mais pas pour l'édition

**Comment by Clm-Roig** [comment]
> 

Je viens d'essayer de faire ça : ça plante "visuellement" mais le nouveau polygone est bien sauvé en base de données. Un retour sur la page du massif le prouve.

**Comment by urien** [comment]
Ok, je regarde dès que possible
