### ISSUE TITLE
Massif description / Description d'un massif

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#753]
When entering data on a massif, the description was recorded 3 times identically in three aborted attempts before final validation.
How could this happen?
What can be done to delete the two unnecessary description texts (editing does not seem to allow this)?

https://grottocenter.org/ui/massifs/8

Lors de la saisie des données sur un massif, la description a été enregistrée 3 fois à l'identique lors de trois essais avortés avant la validation finale.
Comment cela a-t-il pu se produire ?
Comment peut-on faire maintenant pour supprimer les deux textes de description inutiles (l'édition ne semble pas le permettre) ?

**Comment by Clm-Roig** [comment]
Normalement c'est corrigé par #752. Il y avait un souci dans l'édition de massif qui la faisait planter visuellement mais pas dans la base de données : la création des descriptions a, à chaque fois, bien eu lieu. 

Il n'est pour l'instant pas possible de supprimer des descriptions (ou autres infos), mais je pense que c'est quelque chose qui va arriver à court terme...

Je ferme pour l'instant étant donné qu'il n'y a pas réellement de problème. Mais on peut continuer à en discuter même si l'issue est fermée 🙂

**Comment by Clm-Roig** [comment]
Je supprime manuellement les deux descriptions doublons directement dans la base de données.
