### ISSUE TITLE
Ajouter un lien dans le menu principal de GCV3 vers le wiki de Grottocenter

### ISSUE THREAD

**Issue by BTHOM** [GrottoCenter/grottocenter-front#764]
**Is your feature request related to a problem? Please describe.**
Il n'est pas facile d'aller vers le wiki Grottocenter depuis le site GC V3. Quelques liens peu explicites se trouvent tout en bas de la page d'accueil. Aucun lien n'est disponible sur les fiches "cavité" ou "entrée".

**Describe the solution you'd like**
Créer des liens explicites vers le Wiki de Grottocenter; notamment vers la page d'accueil de ce Wiki.
Ces liens pourraient se trouver dans le men de gauche, dans la mesure où il pointe vers un environnement Grottocenter.
**Describe alternatives you've considered**
Un lien pourrait également être placé en haut à droite des fiches encyclopédiques des "entrées" et des "réseaux", à coté du lien vers OpenStreetMap

**Additional context**
None

**Comment by bsoufflet** [comment]
@BTHOM : Cela te conviendrait ?
![image](https://user-images.githubusercontent.com/985903/221067878-00da695b-5fbb-4d02-8f45-6b603afddc28.png)

**Comment by bsoufflet** [comment]
@urien

**Comment by urien** [comment]
Oui c'est bien. Peut être l'enlever du pied de page pour la rendre moins chargée
Merci

**Comment by BTHOM** [comment]
Bonjour,
L'image est tronquée à droite.
@Benjamin, 
Je suppose que tu voulais montrer l'affichage des coordonnées ; or elles n'apparaissent pas du tout...
Un bug sans doute.
En outre, le menu est en anglais.
A+
BTH
 
Envoyé depuis l'application Mail Orange
----------------De : Benjamin S. ***@***.***>Envoyé : vendredi 24 février 2023 02:15À : GrottoCenter/grottocenter-front ***@***.***>Cc : BTHOM ***@***.***>; Mention ***@***.***>Objet : Re: [GrottoCenter/grottocenter-front] Ajouter un lien dans le menu principal de GCV3 vers le wiki de Grottocenter (Issue #764)
@BTHOM : Cela te conviendrait ?

**Comment by urien** [comment]
Bonjour Bernard. Pour voir l'échange il faut cliquer sur view on Github dans le mel que tu reçois

**Comment by BTHOM** [comment]
Merci Frédéric, et Benjamin.
Donc, si j'ai bien compris cette fois, il s'agit d'une ancienne demande concernant l'accès au wiki de Grottocenter via la page d'accueil.
Dans l'état actuel, tel que je peux le voir sur mon Smartphone Samsung, le lien vers le wiki se trouve tout en bas du cadre de gauche, avec les licences.
Je pense qu'il serait mieux à sa place à la suite immédiate des commandes du menu, vers le haut du cadre du gauche.
Merci.
BTH

**Comment by bsoufflet** [comment]
@BTHOM 
Donc le placement en bas du menu de gauche  ne te convient pas ?
![image](https://user-images.githubusercontent.com/985903/221130177-1b8c9f8a-a8ca-45ec-9906-406fd630fbdc.png)
J'ai fait cela pour différencier la navigation interne à grottocenter avec ce lien qui ouvre le wiki dans une nouvelle page.

Tu parlais également de le mettre sur la page d'une entrance : 
> Describe alternatives you've considered
Un lien pourrait également être placé en haut à droite des fiches encyclopédiques des "entrées" et des "réseaux", à coté du lien vers OpenStreetMap
Mais je ne vois pas trop l'intérêt sauf à rediriger vers la page du wiki qui explique spécifiquement la page d'une entrance... Et dans ce cas je mettrais le lien vers le wiki dans ce groupe de bouton ou à coté de ce groupe de bouton...
Mais cela va commencer à faire beaucoup de boutons et poser des problèmes sur mobile...
![image](https://user-images.githubusercontent.com/985903/221130952-11105c42-9695-41ca-bd96-af0a22c70095.png)

(Mes screenshots sont en anglais et c'est normal ;)

**Comment by urien** [comment]
Pour ma part je souhaite qu'il n'existe qu'un lieu vers l'aide en ligne car on n'arrivera pas à maintenir d'autres pages que celle qu'on a qui n'est pas a jour et pas traduite. Les sous-sections des pages peuvent être changées par les utilisateurs, les liens seront rapidement cassés
