### ISSUE TITLE
Enlargement of the map centered on the current cavity (élargissement de la carte centrée sur la cavité en cours)

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#768]
In order to be able to see the cave in its karst environment, it would be necessary to enlarge the map insert of the cave page :

- either by clicking on it 
- or with a specific button "enlarge the map".

This map would show the geographical area surrounding the current cavity and all the cavities surrounding it with an adapted zoom level.

A plus would be that there is a way to quickly distinguish the current cavity on this map (because it can be in an area where many other cavities are visible) either by an icon size difference , or a color difference...

Afin de pouvoir apercevoir la cavité en cours dans son environnement karstique, il serait nécessaire de pouvoir élargir l'encart de carte de la fiche cavité :

- soit en cliquant dessus
- soit avec un bouton spécifique "élargir la carte"

Cette carte présenterait la zone géographique entourant la cavité en cours et toutes les cavités qui l'entourent avec un niveau de zoom adapté.

Un plus serait qu'il y ait un moyen de distinguer rapidement la cavité en cours sur cette carte (car elle peut être dans une zone où de nombreuses autres cavités sont visibles) soit par une différencie de taille de l'icône, soit une différence de couleur...

Example : 
![image](https://user-images.githubusercontent.com/985903/203443159-ff533541-15b4-4c45-bc3f-a11bc833a2dc.png)

**Comment by urien** [comment]
Cette issue a été traitée. Il faudrait faire un nouveau ticket pour demander que les autres cavités du secteur soient également visible, la cavité sélecgtionnée étant d'une couleur différente. Tu veux bien faire ce ticket @Souterweb ?
