### ISSUE TITLE
[DOCUMENT EDIT CREATE] problem with pages of an article

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#784]
**Describe the bug**
Quand je créé ou que j'édite un article il n'est pas possible de mettre le même numéro comme page de début et page de fin, ce qui est indispensable quand l'article ne fait qu'une page.

Si je mets un chiffre en page de fin cela fonctionne mais ce n'est pas satisfaisant.
Si je ne mets qu'une valeur en page de fin et que je valide, ce numéro est enregistré dans le champ page de début, ce qui occasionne un bug qui empêche d'éditer car s'il n'y a qu'une valeur cela doit être dans la page de fin.

**To Reproduce**
- Créer un article et essayer de mettre la même valeur en page de début et page de fin. 
- Tester avec une valeur de page de fin seulement.
- Valider le document.
- Essayer d'éditer le document qui aura été enregistré.

**Expected behavior**
Il faut autoriser un numéro de page de début et de fin égaux.

Ce serait bien que ce soit réalisé pour le 18 janvier, date de la prochaine conférence de présentation du BBS.

**Comment by Clm-Roig** [comment]
> Si je ne mets qu'une valeur en page de fin et que je valide, ce numéro est enregistré dans le champ page de début, ce qui occasionne un bug qui empêche d'éditer car s'il n'y a qu'une valeur cela doit être dans la page de fin.

Cela pourrait faire l'objet d'un nouveau ticket. Il y a des raisons pour lesquelles on avait autorisé que le champ "fin" puisse être le seul rempli mais ça demande un traitement particulier côté serveur qui n'est pas fait.

**Comment by urien** [comment]
En fait le besoin est de pouvoir mettre la même valeur au début et à la fin. A défaut de pouvoir le faire les utilisateur indiquent uniquement la page de fin pour pouvoir continuer

**Comment by Clm-Roig** [comment]
Oui oui et j'ai répondu à ce besoin ici #792. 

Indépendamment de ça, il n'empêche que le fait de mettre uniquement un numéro de fin entraîne bel et bien un bug (que tu mentionnes). D'où le fait que je demande une autre issue pour discuter du fix à apporter à ce deuxième bug.

**Comment by urien** [comment]
J'ai fait une nouvelle issue https://github.com/GrottoCenter/grottocenter-front/issues/793
