### ISSUE TITLE
[DOCUMENT FORM] Make editor field available for all document types

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#785]
**Is your feature request related to a problem? Please describe.**
Pour certains types de document il n'est pas possible de rajouter un éditeur

**Describe the solution you'd like**
Il faudrait rajouter ce champ pour tous les types de documents qui ne l'on pas et qui auraient besoin d'en bénéficier, à la création et à l'édition

**Comment by Clm-Roig** [comment]
Il me faudrait la liste des documents pour lesquels tu veux activer (ou désactiver) la possibilité d'ajouter un éditeur. 
Pour le moment, c'est autorisé sur : 
- Collection
- Issue
- Article


Les autres types sont : 
- Dataset
- Event
- Image
- Service
- Software
- Sound
- Text
- Book
- Map
- Physical Object
- Interactive Resource
- Moving Image
- Topographic Drawing
- Topographic Data
- Authorization To Publish
- Still Image

**Comment by urien** [comment]
Je pense qu'on peut l'activer pour tous, sans que ce soit obligatoire

**Comment by Clm-Roig** [comment]
C'est ce que je me disais, ce sera plus simple. Je fais ça de suite, merci !
