### ISSUE TITLE
[DOCUMENT CREATE EDIT] Uploading a file make an error

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#795]
**Describe the bug**
Quand je souhaite valider un document qui a un fichier associer il n'est pas possible de valider, dans la console j'ai une erreur Une chaîne vide a été transmise à « getElementById() ».

**To Reproduce**

1. Go to 'https://grottocenter.org/ui/documents/37575'
2. Click on 'Edit'
3. Add file https://cds05.fr/wp-content/uploads/2016/12/Voconcie19.pdf
4. with autorization to publish Voconcie, licence CC BY NC ND

**Comment by Clm-Roig** [comment]
Je viens de faire ce que tu expliques dans "To Reproduce" et ça a marché sur la prod. 
Le document était un peu lourd, j'ai dû attendre un peu pour que l'édition se passe bien. Pour la validation, aucun souci.

Est-ce que tu avais bien attendu après avoir cliqué sur "Mise à jour" ? Je ne vois as d'où ça peut venir sinon...

**Comment by urien** [comment]
Le bouton mise a jour était inactif. J'ai cliqué plusieurs fois et cela a planté l'appli. Quand elle a refonctioné j'ai réessayé avec la console avec le même résultat et l'erreur que j'ai indiquée.
Je vais réessayer dans la journée

**Comment by Clm-Roig** [comment]
Le bouton Mise à jour "final" de la toute fin du formulaire ? Je ne crois pas que celui puisse être inactif. 
Tu parles peut-être du bouton "suivant" de l'étape d'ajout de fichiers ?

**Comment by urien** [comment]
Si, le bouton final, "mise a jour" ne produisait rien et dans la console j'avais l'erreur indiquée. Je vais réessayer

**Comment by Clm-Roig** [comment]
Ok ! Donc il n'était pas inactif : tu as cliqué une première fois puis rien ne se passait pour ce premier clic, comme pour les autres si j'ai bien compris.

**Comment by urien** [comment]
Oui, je me demande si l'ordre n'était pas inverse : l'appli était plantée avant que je demande à mettre à jour le document (plutot que la mise à jour du document à planté l'appli). Cela expliquerait pourquoi cela fonctionne maintenant

**Comment by urien** [comment]
C'est ok maintenant
