### ISSUE TITLE
[DOCUMENT CREATION EDITION] Possibilité de retirer l'association à un massif

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#803]
Quand on sélectionne un massif, ou quand un massif est déjà associé à un document il n'est pas possible de retirer ce lien au massif

![Image](https://user-images.githubusercontent.com/1165144/222077904-2a681703-28a6-473d-9af0-419824198ad4.png)

La solution est de proposer un bouton comme pour les autres champs, le fait de cliquer sur la x permettant de retirer le massif sélectionné

![Image](https://user-images.githubusercontent.com/1165144/222078077-0b689f4f-d411-4b06-adbc-b4ee0c9403af.png)

**Comment by Souterweb** [comment]
Pour le choix d'un massif la solution proposée ne me semble pas convenir car la liste n’apparait pas en entier : seules apparaissent les proposition correspondant aux premières lettres saisies. Il faudrait quelque part un bouton ou un lien d’effacement de la zone de saisie.

**Comment by Clm-Roig** [comment]
@Souterweb tu peux saisir ton issue uniquement en français si tu le souhaites : pour l'instant, tous les développeurs sont francophones. On traduira en anglais au cas par cas si nécessaire.

**Comment by urien** [comment]
Désormais l'association se fait sur la page du massif
