### ISSUE TITLE
[ENTRANCE EDIT] Problem with the name

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#810]
**Describe the bug**
1 Quand on édite une entrée, le nom de celle-ci n'est pas recopié dans le formulaire. Il faut donc le ressaisir pour continuer
2 Quand on édite une entrée qui fait partie d'un réseau le nom n'apparait pas et il n'est pas possible de le saisir et donc de continuer

**To Reproduce**
Steps to reproduce the behavior 1:

1. Go to 'https://grottocenter.org/ui/entrances/24564'
2. Click on 'Edit'
3. See error

![image](https://user-images.githubusercontent.com/1165144/209951281-ef75c137-3963-4422-80f5-35dc803d1641.png)

Steps to reproduce the behavior 2:

1. Go to 'https://grottocenter.org/ui/entrances/23750'
2. Click on 'Edit'
3. See error
![image](https://user-images.githubusercontent.com/1165144/209951448-c86bef82-4482-4d9d-bfdf-acbedebe0ef5.png)

**Comment by vmarseguerra** [comment]
Problème résolut depuis #787 je pense. Le nom apparait maintenant bien sur les 2 pages:
https://grottocenter.org/ui/entrances/24564
https://grottocenter.org/ui/entrances/23750

**Comment by urien** [comment]
Merci Vincent
