### ISSUE TITLE
[DOCUMENT CREATE EDIT] .tro file error

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#824]
**Describe the bug**
Je souhaite associer des fichiers .tro à un document. Lors de la création le document a été créé sans les fichiers, à l'édition j'ai un message d'erreur :
`PUT https://api.grottocenter.org/api/v1/documents/145822`

```
[HTTP/2 400 Bad Request 518ms]
Uncaught (in promise) Error: Fetching function(e){return"".concat(lu,"/documents/").concat(e)} status: 400
```

**To Reproduce**

Voila les fichiers .tro que je souhaite associer à ce document (dans un zip car Github refuse ce type de fichier)
[tanne_mine_de_charbon.zip](https://github.com/GrottoCenter/grottocenter-front/files/10368196/tanne_mine_de_charbon.zip)

**Comment by urien** [comment]
En fait la liste des extensions réellement autorisée est différente de cette qui figure dans la page. les fichiers topo .th et .th2 par exemple ne passent pas non plus. cela va poser un problèmes assez rapidement

**Comment by bsoufflet** [comment]
Done by fixing the MIME types in database using https://github.com/jshttp/mime-db/blob/master/db.json
