### ISSUE TITLE
[ENTRANCE Location] Edition don't work

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#827]
**Describe the bug**
Quand on édite une localisation la mise à jour n'est pas prise en compte

**To Reproduce**
https://grottocenter.org/ui/entrances/34392
Editer la location en indiquant un titre et la langue française. Après avoir cliqué sur mise à jour le bloc localisation n'est pas mis à jour

**Comment by bsoufflet** [comment]
FIxed directly in production BDD by reapplying the histo_update_location() PSQL function
