### ISSUE TITLE
Problème de mise à jour des massifs (polygone)

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#838]
Quand on édite un massif et qu'on modifie le polygone qui le limite, le nouveau périmètre n'est pas pris en compte après l'enregistrement de la page. La limite du massif reste comme elle était.

**Comment by urien** [comment]
Traité par Vincent. Merci pour ce ticket @Souterweb

**Comment by Souterweb** [comment]
Bizarre, je viens encore d'essayer de modifier le contour d'un massif et après validation rien ne semble avoir changé. Faut-il (comme pour d'autres mises à jour) attendre un moment pour que ce soit entériné ?

**Comment by vmarseguerra** [comment]
Je viens d'essayer et je n'ai pas de soucis pour modifier le contour du massif:
https://grottocenter.org/ui/massifs/596

As-tu bien cliqué sur "Save" avant de valider la mise à jour ?
![image](https://user-images.githubusercontent.com/6350275/217920205-5642a814-829e-4e28-a9da-912578dda348.png)

**Comment by Souterweb** [comment]
Le 09/02/2023 à 20:43, Vincent Marseguerra a écrit :
> As-tu bien cliqué sur "Save" avant de valider la mise à jour ?
> image 
> <https://user-images.githubusercontent.com/6350275/217920205-5642a814-829e-4e28-a9da-912578dda348.png>

Bigre : je n'ai jamais vu ce bouton "Save"...

Domi

**Comment by Souterweb** [comment]
Le 09/02/2023 à 20:43, Vincent Marseguerra a écrit :
> As-tu bien cliqué sur "Save" avant de valider la mise à jour ?

Je n'avais jamais vu ce bouton "Save" : si on ne me l'avait pas signalé 
jamais je ne l'aurais trouvé. Merci pour l'info et l'image.

Donc mon expérience d'utilisateur c'est que ce bouton est bien trop 
discret et/ou mal placé.

Sinon effectivement ça fonctionne bien.

Domi
