### ISSUE TITLE
[ORGANISATION Create] Don't work

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#861]
**Describe the bug**
Quand on souhaite créer une organisation depuis le formulaire de création d'un document ou directement depuis le formulaire de création d'une organisation la requete n'aboutit pas

**To Reproduce**
Tentative de création de la Société Spéléologique du Plantaurel

**Comment by urien** [comment]
En fait les organisations ont bien été créées même si le formulaire affichait un message d'erreur et que le processus n'allait pas à son terme

**Comment by bsoufflet** [comment]
Impossible de reproduire ce problème. La création fonctionne pour moi.
@urien

**Comment by urien** [comment]
effectivement cela fonctionne bien
