### ISSUE TITLE
Plantage ?

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#864]
Je viens d'avoir ceci : 

Désolé, quelque chose s'est mal passé....
This issue occurred while you were trying to reach the following address: /ui/entrances/24784/snapshots

Je n'en sais pas plus.

**Comment by Souterweb** [comment]
Et apparemment ça le fait sur chaque fiche cavité quand on clique sur l'icône "Access to general entrance page", car j'ai eu aussi : 

Désolé, quelque chose s'est mal passé....
This issue occurred while you were trying to reach the following address: /ui/entrances/40/snapshots

**Comment by bsoufflet** [comment]
C'est corrigé et ce sera deploy rapidement :) @Souterweb : lors de la création d'une issue sur github essai de mettre un titre plus explicite :) Par exemple `Impossible d'accéder à la page général des versions d'une entrée` au lieu de `Plantage ?` ;)
