### ISSUE TITLE
Gestion des informations de localisation administrative

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#869]
**Is your feature request related to a problem? Please describe.**
Les entités administratives que nous souhaitons gérer sont
- le pays
- Admin1 (les régions en France)
- Adlin2 (les départements en France)
Cette gestion est basée sur une liste contrôlée d'entités administratives, définie au niveau international. Les contributeurs et les administrateurs de Grottocenter se conforment aux décisions des instances internationales en matière de reconnaissance des pays et de leurs frontières ou de leur découpage administratif interne

Les besoins sont les suivants
- Afficher les informations de localisation administrative dans la langue retenue pour Grottocenter
- Faire une recherche par entité administrative dans la langue retenue pour Grottocenter
-  Afficher une page par entité administrative avec la liste des cavités, des organisations, des documents, des massifs, des données statistiques la liste des entités administratives de niveau inférieur, le périmètre de cette entité administrative
- Mettre à jour les informations stockées : tables de pays, région, département si c'est nous qui les gérons. Informations sur la localisation administrative stockées dans les tables des entrées, documents, organisations. La base actuelle contient les informations de régions et de département dans un seul champ (issu de la V2). Elle doit être entièrement nettoyée, ce nettoyage devra être réalisé périodiquement en fonction des changement de frontière ou de découpage administratif au sein d'un pays.
- A partir des coordonnées fournir automatiquement les données de localisation administrative *pour les entrées et les organisations*. La possibilité de déroger à la réponse fournie automatiquement pourra faire l'objet d'un ticket séparé si cela correspond à une demande
- *Pour les documents* : à partir du choix d'un pays permettre à l'utilisateur de choisir une région puis un département

- Afficher

**Describe the solution you'd like**
Utiliser https://osm2pgsql.org/ pour récupérer les données à jour sur les pays, les régions, les département. L'installation d'un serveur nominatim qui récupère uniquement les données pays, admin1 et admin2 et qui fournirait des apis de reverse geocoding permettrait de répondre à tous nos besoins https://nominatim.org/release-docs/latest/admin/Installation/
Créer les fonctionnalités attendues à partir des données que nous stockons

**Describe alternatives you've considered**
Utiliser les Apis de Google

**Comment by BTHOM** [comment]
Bonsoir,

Je ne reconnais pas dans ce "ticket-issue" n°869 les consensus auxquels nous étions parvenus concernant les niveaux d'entités administrative à gérer. Il faut dire que c'était il y a fort longtemps (2020 ?) et qu'il y a donc eu de la perte en ligne.

Bref, à cette époque nous parlions de 5 niveaux de localisation administrative :: 
 niveau 1 : le pays 
 niveau 2 : l'état, le land,...  (pour les pays fédéraux) ou la région, la province,... (pour les pays centralisés)
 niveau 3 : le comté, le département,.la comarque..
 niveau 4 : la commune, la municipalité, la ville,...
 niveau 5 : le lieu-dit, la section communale, la commune déléguée,...

En cas de niveau intermédiaire supplémentaire (arrondissement, quartier), la solution consiste à indiquer cette entité supplémentaire après virgule, dans le champ de l'entité de niveau inférieur. Par exemple : 
France (FR) ; Provence-Alpes-Côte d'Azur (PAC) ; Vaucluse (84) ; Pertuis (84089), arrondissement d'Apt ; La Loubière.
 
De plus, comme indiqué dans l'exemple ci-dessus, l'ajout des codes officiels ISO ou des codes locaux (INSEE,...) permet de résoudre les ambiguïtés, notamment les homonymies et les problèmes de langue.

A propos de langue,  le "besoin" de "Afficher les informations de localisation administrative dans la langue retenue pour Grottocenter" ne me paraît pas pertinent. Le nom des entités devrait plutôt être écrit dans la langue du pays où se trouve cette entité, sinon chacun voudra traduire ces informations dans sa propre langue ce qui entrainera de nouvelles ambiguïtés.
Eventuellement, une transcription pourra être ajoutée après virgule notamment en cas d'alphabet non roman.

Enfin, la détermination automatique des entités administratives à partir des coordonnées doit rester une aide à la saisie mais ne doit pas forcer le choix du contributeur. En effet, dans la littérature, de nombreuses coordonnées sont imprécises voire erronées ; l'entité administrative est alors l'information de localisation la plus fiable, à condition qu'elle ne soit pas biaisée par une détermination automatique.

**Comment by urien** [comment]
`5 niveaux de localisation administrative` Au niveau de la norme il existe les pays puis les niveaux Admin1, 2,3. Admin 1 correspond à l'état, la région, la province.

Je propose de nous limiter à Admin1 et Admin2 car les inventaires sont en général nationaux ou au niveau Admin1. Le niveau Admin2 ne présentera d’intérêt que pour la France.

'En cas de niveau intermédiaire supplémentaire (arrondissement, quartier), la solution consiste à indiquer cette entité supplémentaire après virgule, dans le champ de l'entité de niveau inférieur'
Afin de pouvoir fournir des traductions, des outils de recherche, des cartes, je propose de  se baser sur des listes fournies par des services extérieurs. Je propose d'utiliser un outils qui permet de récupérer les informations d'OSM. Il ne sera possible d'associer aux champs Admin1 et Admin2 que des entités qui existent, qu'on peut représenter sur la carte, dont le nom est fourni dans différentes langues, dans différents alphabets
Au niveau base de données Admin1 doit correspondre à 5000 entités dans le monde, Admin2 à 50 000. Au delà on se retrouve avec des bases de données qui ne sont pas exhaustives, des volumes de données très importants qui nécessitent des machines dédiées

'Le nom des entités devrait plutôt être écrit dans la langue du pays'
Il n'est pas possible de se baser sur la langue du pays car de nombreux pays ont plusieurs langues (4 pour mes voisins les Suisses). Il n'est guère possible de lire et d'écrire dans tous les alphabets utilisés par toutes les langues. On ne pourra pas faire des recherches sur des bases locales pour collecter les identifiants locaux. Ce code pourra être archivé si cela présente un intérêt pour les utilisateurs et si c'est disponible 

'Enfin, la détermination automatique des entités administratives à partir des coordonnées doit rester une aide à la saisie mais ne doit pas forcer le choix du contributeur'
Je propose que ce soit la règle de proposer une réponse automatique. S'il est souhaité que les contributeurs puissent déroger à ce qui est proposé il faut faire un ticket qui précise les régles qui vont s'appliquer

**Comment by urien** [comment]
Le ticket a été réglé, si des besoins persistent il conviendra de reformuler un ticket
