### ISSUE TITLE
Affichage des révisions d'une fiche

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/grottocenter-front#882]
Ave,

Quand j'ai cliqué sur l'exemple donné dans l'issue #679 : https://grottocenter.org/ui/entrances/6224 j'ai ensuite testé le bouton "TOUTES LES RÉVISIONS" et j’ai obtenu ceci :

_Déso_lé, quelque chose s'est mal passé....
This issue occurred while you were trying to reach the following address: /ui/entrances/6224/snapshots
Merci de contacter l'association Wikicaves pour l'informer de ce bug : http://fr.wikicaves.org/contact
[Vous pouvez également créer directement un nouveau ticket sur la page GitHub de Grottocenter.](https://github.com/GrottoCenter/grottocenter-front/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=)__

Donc j'ai fait un ticket comme indiqué. 
Mais je me demande si ça n'avait pas déjà été signalé (doublon) ?

Domi

**Comment by urien** [comment]
Il y a déjà un ticket 😉
https://github.com/GrottoCenter/grottocenter-front/issues/868
