### ISSUE TITLE
[DOCUMENT CREATE EDIT] Can't watch the languages

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#885]
**Describe the bug**
Quand on créé ou qu'on édite un document il faut saisir 3 lettre pour que soient proposées des langues. On a alors un bloc qui s'ouvre sans rien contenir de visible, mais si on clique dedans on peut tout de même sélectionner une langue qui est proposée, sans être visible
![image](https://user-images.githubusercontent.com/1165144/222074259-4f906151-6fe1-4167-802d-5be0eb53f89f.png)

**To Reproduce**
Choisir un document existant
demander à l'éditer
dans le champ langue du document ou dans le champ langue de la description saisir 3 lettres (fra). Dans la petite fen^tre qui s'ouvre et qui ne continent rien de visible cliquer en haut pour sélectionner le Français

**Comment by Souterweb** [comment]
Exact, j'avais déjà remarqué ça mais j’ai oublié de le signaler sur le moment...
