### ISSUE TITLE
[DOCUMENT CREATE EDIT] Tous les fichiers qui devraient être acceptés ne passent pas

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#889]
**Describe the bug**

Il y a une différence entre la liste des extensions affichées, la liste des extensions qui s'affichent quand on recherche des fichiers et les fichiers qui peuvent réellement être importés. Une erreur silencieuse est générée

La liste des extensions autorisées est affichée sur le site

![image](https://user-images.githubusercontent.com/1165144/223409790-5f3e1b87-3064-4cd2-96ff-deffd660deb3.png)

J'ai préparé un dossier qui continent au moins un fichier avec chaque extension autorisée
![image](https://user-images.githubusercontent.com/1165144/223410038-c326d2b9-ae04-4612-b076-bd834a12b4d3.png)

Si je souhaite importer tous ces fichiers dans un document, il y a seuelemtn une partie des fichiers qui apparaissent comme ayant une extension autorisée
![image](https://user-images.githubusercontent.com/1165144/223410357-02e8ecff-5020-4d16-800e-9ced1c902d20.png)

Si je sélectionne tous les fichiers (en demandant à afficher tous les fichiers), ils apparaissent tous comme valides
J'ai une erreur sans message d'information (l'erreur est visible dans la cosole) lorsque je valide
![image](https://user-images.githubusercontent.com/1165144/223413658-ac228158-8db9-4b71-af98-85a983500631.png)

Les fichiers .kmz .avi .bmp .csv .cxf .dxf .gpx .gsm .gz .h++ .kml .obj .pcx .pl .taz .xcf .xml .xyz .zip génèrent une erreur

Les fichiers qui passent sont les suivants
![image](https://user-images.githubusercontent.com/1165144/223433797-a7b2942a-d4ad-4eaf-9fee-a097dd240295.png)

les tests ont été réalisés sur https://grottocenter.org/ui/documents/45510

**Comment by bsoufflet** [comment]
@urien : Peux tu mettre à dispo ta liste de fichiers de test sur ce ticket ?

**Comment by urien** [comment]
[fichierstest.txt](https://github.com/GrottoCenter/grottocenter-front/files/11038593/fichierstest.txt)
Il faut renommer le fichier avec l'extension .zip
Github n'accepte pas toutes les extensions

**Comment by urien** [comment]
Tout est ok
