### ISSUE TITLE
[ENTRANCE CREATE] Blocage à la création

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#904]
**Describe the bug**
A la création d'une entrée Laurent Guyot se retrouve face à une requête qui n'aboutit pas quand il valide la création.
Il obtient cela 
![2023-04-26 16_06_35-Window](https://user-images.githubusercontent.com/1165144/234602769-68a97294-a530-4dd9-9f58-0536bf3ef43f.png)

**Comment by urien** [comment]
C'est sur une machine sous Windows 11 avec Chrome dans le cadre d'une navigation privée

**Comment by urien** [comment]
C'est le problème de Virgile dans les coordonnées. La question a été prise en charge par Vincent.

**Comment by BTHOM** [comment]
Sacré Virgile !
Il mérite qu'on l'apostrophe !
;-)
 
Envoyé depuis l'application Mail Orange
----------------De : "Frédéric Urien" ***@***.***>Envoyé : mardi 02 mai 2023 11:25À : GrottoCenter/grottocenter-front ***@***.***>Cc : Subscribed ***@***.***>Objet : Re: [GrottoCenter/grottocenter-front] [ENTRANCE CREATE] Blocage à la création (Issue #904)
C'est le problème de Virgile dans les coordonnées. La question a été prise en charge par Vincent.
