### ISSUE TITLE
Format ISSN non reconnu pour un document

### ISSUE THREAD

**Issue by Xtof054** [GrottoCenter/grottocenter-front#960]
**Describe the bug**
Lors de la création d'un document le numéro ISSN n'est pas reconnu comme conforme.
N° concerné : 0338-425X
Vérification de l'existence du numéro : https://portal.issn.org/resource/issn/0338-425x

**Expected behavior**
Merci de corriger les formats acceptés pour les ISSN.

**Screenshots**
![image](https://github.com/GrottoCenter/grottocenter-front/assets/116448409/2e099954-8e53-4994-bba8-73fa7bd24309)

**Comment by vmarseguerra** [comment]
Merci pour ce retour.

Je viens de modifier la Regex de validation de l'ISSN en base de données pour accepter aussi le `X` majuscule comme dernier caractère

Ainsi: 
`^[0-9]{4}-[0-9]{3}[0-9x]$`
devient: 
`^[0-9]{4}-[0-9]{3}[0-9xX]$`

Le problème devrait être résolu.
