### ISSUE TITLE
Bug d'affichage des fiches entrée

### ISSUE THREAD

**Issue by BTHOM** [GrottoCenter/grottocenter-front#973]
**Describe the bug**
Les fiches 'entrée' ne s'affichent pas complètement. 
L'affichage de la fiche s'arrête avant que les données et la carte n'apparaissent.
Seul apparaissent le cadre gris (destiné à afficher la carte), le bandeau pour imprimer, modifier la fiche ou accéder à son historique et quelques icones. 
Et encore, si on clique sur le bouton d'édition (crayon), cela déclenche le message d'erreur 'Désolé, quelque chose s'est mal passé..'

**To Reproduce**
Par exemple : https://grottocenter.org/ui/entrances/37388

**Expected behavior**
La fiche entrée devrait afficher toutes les informations habituelles (propriétés, carte, sections encyclopédiques)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 7 Professionnel 64 bits + Service Pack 1
- Browser : Chrome
- Version: 109.0.5414.120 (Build officiel) (64 bits)

**Smartphone (please complete the following information):**
OK

**Additional context**
Ce bug est apparu, avec d'autres phénomènes (moteur de recherche inopérant, lenteurs voire time-out) après que j'ai installé l'antivirus Avast gratuit.
J'ai pu corriger certains problèmes en déclarant dans les paramètres de l'antivirus des sites en 'exception' (notamment grottocenter.org ; openstreetmap.org ; chrome.fr ; google.com, etc,)
Visiblement, certains blocages persistent, peut être liés à des API ou autres applications que je devrais également déclarer en exception pour mon antivirus. Mais je ne sais pas lesquelles....

**Comment by urien** [comment]
Bonjour Bernard,

Ce problème semble lié à Avast et pas avec Grottocenter. Je ne vois pas ce que l'on peut faire au niveau de nos applications.
Je te propose de regarder dans Avast : il doit y avoir un endroit où l'on peut accéder aux sites qui ont été bloqués ou un endroit où l'on peut définir le niveau de protection de manière globale et que tu retienne une protection moins stricte

**Comment by urien** [comment]
Je pense que tu auras les réponses dans le code source, par exemple pour la page d'accueil il y a les url qui sont appelées 
view-source:https://grottocenter.org/

Je te propose de fermer ce ticket : il n'y a rien a faire dans le code de Grottocenter pour régler ce pb

**Comment by BTHOM** [comment]
Ok pour la fermeture du ticket.
Ç'aura été un exercice github pour moi.
Et maintenant je vais essayer de trouver quelques aiguilles dans la botte de foin du code source...re
A+
BTH
 
Envoyé depuis l'application Mail Orange
----------------De : "Frédéric Urien" ***@***.***>Envoyé : lundi 17 juin 2024 10:37À : GrottoCenter/grottocenter-front ***@***.***>Cc : BTHOM ***@***.***>; Author ***@***.***>Objet : Re: [GrottoCenter/grottocenter-front] Bug d'affichage des fiches entrée (Issue #973)
Je pense que tu auras les réponses dans le code source, par exemple pour la page d'accueil il y a les url qui sont appelées
view-source:https://grottocenter.org/
Je te propose de fermer ce ticket : il n'y a rien a faire dans le code de Grottocenter pour régler ce pb
