### ISSUE TITLE
[IMPORT DOCUMENT] importation du résumé

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#984]
**Describe the bug**
Lorsque j'importe un document via csv, la partie "résumé" ne s'importe plus. C'est très problèmatique car j'ai 300 documents à importer et il y en a plusieurs miliers qui sont annoncés

**To Reproduce**
Voila le fichier que j'ai importé pour ce ticket 
[import analyses Belgique_ligne_1.csv](https://github.com/user-attachments/files/16780700/import.analyses.Belgique_ligne_1.csv)
Le document produit ne contient pas de résumé
https://grottocenter.org/ui/documents/224776

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-api/pull/1322
