### ISSUE TITLE
[DOCUMENT EDIT] Les fichiers csv ne passent pas

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#986]
**Describe the bug**
J'ai édité un document en ne l'associant qu'a des fichiers wslx et c'est passé
https://grottocenter.org/ui/documents/223890
Par contre si je mets aussi des fichiers csv cela plante
![image](https://github.com/user-attachments/assets/565b106d-ad59-4faa-870a-a591891c618b)

**To Reproduce**
les fichiers csv qui doivent être associés a ce document

[2014-Rognes-K-Tremie-09566.csv](https://github.com/user-attachments/files/16796867/2014-Rognes-K-Tremie-09566.csv)
[2014-Rognes-J-Glory-09997.csv](https://github.com/user-attachments/files/16796877/2014-Rognes-J-Glory-09997.csv)

**Comment by vmarseguerra** [comment]
@urien Je crois que le problème a été corrigé avec https://github.com/GrottoCenter/grottocenter-api/pull/1322. Tu pourrais réessayer ?

**Comment by urien** [comment]
Oui @vmarseguerra , je viens faire un test de cavité et c'est passé
