### ISSUE TITLE
[Export CSV] Ne fonctionne pas

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#987]
**Describe the bug**
Quand on fait une recherche avancée il est normalement possible d'exporter les résultats au format CSV.

Actuellement cela ne fonctionne pas

La réparation de ce bug est une demande de Patrick Deriaz

![image](https://github.com/user-attachments/assets/537d52ed-e956-4e1e-8e7a-ec7759c323d6)

**Comment by BTHOM** [comment]
Bonjour à tous,
Si vous travaillez sur la recherche avancée,  serait il possible de classer les résultats par date et/ou par ordre alphabétique ?
Merci

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-front/pull/1012
