### ISSUE TITLE
La date de création de chaque fiche d'entrée n'apparaît plus à coté du nom du créateur de la fiche.

### ISSUE THREAD

**Issue by BTHOM** [GrottoCenter/grottocenter-front#992]
**Describe the bug**
La date de création de chaque fiche d'entrée n'apparaît plus à coté du nom du créateur de la fiche.
De plus, l'historique des versions n'est plus accessible : un message d'erreur apparaît lorsqu'on clique sur le bouton de l'historique des révisions.

**To Reproduce**
Observer une fiche d'entrée pour constater l'absence de date
Cliquer sur le bouton de l'historique des révisions pour constater le message d'erreur

**Expected behavior**
Rétablir l'affichage de la date de création.
Rétablir l'affichage de l'historique des révisions

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser : Chrome

**Smartphone (please complete the following information):**
Non testé

**Additional context**
Ces bugs semblent apparentés à une récente évolution importante de l'interface concernant notamment les fiches d'entrée.

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-front/pull/1012
